package net.tintankgames.marvel.world.item;

import net.minecraft.core.component.DataComponents;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.*;
import net.minecraft.world.item.component.ChargedProjectiles;
import net.minecraft.world.item.crafting.Ingredient;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.common.DeferredSpawnEggItem;
import net.neoforged.neoforge.event.brewing.RegisterBrewingRecipesEvent;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.tintankgames.marvel.MarvelSuperheroes;
import net.tintankgames.marvel.core.components.MarvelDataComponents;
import net.tintankgames.marvel.world.entity.MarvelEntityTypes;
import net.tintankgames.marvel.world.item.component.Size;
import net.tintankgames.marvel.world.level.block.MarvelBlocks;
import net.tintankgames.marvel.world.level.block.entity.MarvelBannerPatterns;

import java.util.List;
import java.util.function.Supplier;

@EventBusSubscriber
public class MarvelItems {
    private static final DeferredRegister.Items REGISTER = DeferredRegister.createItems(MarvelSuperheroes.MOD_ID);

    public static final DeferredItem<Item> VIBRANIUM = register("vibranium", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON).fireResistant()));
    public static final DeferredItem<Item> VIBRANIUM_INGOT = register("vibranium_ingot", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON).fireResistant()));
    public static final DeferredItem<Item> VIBRANIUM_NUGGET = register("vibranium_nugget", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON).fireResistant()));
    public static final DeferredItem<Item> VIBRANIUM_SWORD = register("vibranium_sword", () -> new SwordItem(MarvelTiers.VIBRANIUM, new Item.Properties().rarity(Rarity.UNCOMMON).fireResistant().attributes(SwordItem.createAttributes(MarvelTiers.VIBRANIUM, 3, -2.4F))));
    public static final DeferredItem<Item> VIBRANIUM_SHOVEL = register("vibranium_shovel", () -> new ShovelItem(MarvelTiers.VIBRANIUM, new Item.Properties().rarity(Rarity.UNCOMMON).fireResistant().attributes(ShovelItem.createAttributes(MarvelTiers.VIBRANIUM, 1.5F, -3.0F))));
    public static final DeferredItem<Item> VIBRANIUM_PICKAXE = register("vibranium_pickaxe", () -> new PickaxeItem(MarvelTiers.VIBRANIUM, new Item.Properties().rarity(Rarity.UNCOMMON).fireResistant().attributes(PickaxeItem.createAttributes(MarvelTiers.VIBRANIUM, 1.0F, -2.8F))));
    public static final DeferredItem<Item> VIBRANIUM_AXE = register("vibranium_axe", () -> new AxeItem(MarvelTiers.VIBRANIUM, new Item.Properties().rarity(Rarity.UNCOMMON).fireResistant().attributes(AxeItem.createAttributes(MarvelTiers.VIBRANIUM, 5.0F, -3.0F))));
    public static final DeferredItem<Item> VIBRANIUM_HOE = register("vibranium_hoe", () -> new HoeItem(MarvelTiers.VIBRANIUM, new Item.Properties().rarity(Rarity.UNCOMMON).fireResistant().attributes(HoeItem.createAttributes(MarvelTiers.VIBRANIUM, -4.0F, 0.0F))));
    public static final DeferredItem<Item> VIBRANIUM_HELMET = register("vibranium_helmet", () -> new ArmorItem(MarvelArmorMaterials.VIBRANIUM, ArmorItem.Type.HELMET, new Item.Properties().rarity(Rarity.UNCOMMON).fireResistant().durability(ArmorItem.Type.HELMET.getDurability(45))));
    public static final DeferredItem<Item> VIBRANIUM_CHESTPLATE = register("vibranium_chestplate", () -> new ArmorItem(MarvelArmorMaterials.VIBRANIUM, ArmorItem.Type.CHESTPLATE, new Item.Properties().rarity(Rarity.UNCOMMON).fireResistant().durability(ArmorItem.Type.CHESTPLATE.getDurability(45))));
    public static final DeferredItem<Item> VIBRANIUM_LEGGINGS = register("vibranium_leggings", () -> new ArmorItem(MarvelArmorMaterials.VIBRANIUM, ArmorItem.Type.LEGGINGS, new Item.Properties().rarity(Rarity.UNCOMMON).fireResistant().durability(ArmorItem.Type.LEGGINGS.getDurability(45))));
    public static final DeferredItem<Item> VIBRANIUM_BOOTS = register("vibranium_boots", () -> new ArmorItem(MarvelArmorMaterials.VIBRANIUM, ArmorItem.Type.BOOTS, new Item.Properties().rarity(Rarity.UNCOMMON).fireResistant().durability(ArmorItem.Type.BOOTS.getDurability(45))));
    public static final DeferredItem<Item> RAW_TITANIUM = register("raw_titanium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> TITANIUM_INGOT = register("titanium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> TITANIUM_NUGGET = register("titanium_nugget", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RAW_PALLADIUM = register("raw_palladium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> PALLADIUM_INGOT = register("palladium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> PALLADIUM_NUGGET = register("palladium_nugget", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> GOLD_TITANIUM_INGOT = register("gold_titanium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> GOLD_TITANIUM_NUGGET = register("gold_titanium_nugget", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> ADAMANTIUM_INGOT = register("adamantium_ingot", () -> new Item(new Item.Properties().fireResistant().rarity(Rarity.UNCOMMON)));
    public static final DeferredItem<Item> ADAMANTIUM_NUGGET = register("adamantium_nugget", () -> new Item(new Item.Properties().fireResistant().rarity(Rarity.UNCOMMON)));
    public static final DeferredItem<Item> PROTO_ADAMANTIUM_INGOT = register("proto_adamantium_ingot", () -> new Item(new Item.Properties().fireResistant().rarity(Rarity.UNCOMMON)));
    public static final DeferredItem<Item> PROTO_ADAMANTIUM_NUGGET = register("proto_adamantium_nugget", () -> new Item(new Item.Properties().fireResistant().rarity(Rarity.UNCOMMON)));
    public static final DeferredItem<Item> URU_INGOT = register("uru_ingot", () -> new Item(new Item.Properties().rarity(Rarity.RARE).fireResistant()));
    public static final DeferredItem<Item> URU_NUGGET = register("uru_nugget", () -> new Item(new Item.Properties().rarity(Rarity.RARE).fireResistant()));
    public static final DeferredItem<Item> REINFORCED_LEATHER = register("reinforced_leather", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> VIBRANIUM_WEAVE = register("vibranium_weave", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON).fireResistant()));
    public static final DeferredItem<Item> VIBRANIUM_NANITES = register("vibranium_nanites", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON).fireResistant()));
    public static final DeferredItem<Item> UNSTABLE_PYM_PARTICLE = register("unstable_pym_particle", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> PYM_PARTICLE = register("pym_particle", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> SYRINGE = register("syringe", () -> new SyringeItem(new Item.Properties()));
    public static final DeferredItem<Item> VILLAGER_BLOOD_SAMPLE = register("villager_blood_sample", () -> new VillagerBloodSampleItem(new Item.Properties().stacksTo(1)));
    public static final DeferredItem<Item> X_GENES = register("x_genes", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> HYDRA_BANNER_PATTERN = register("hydra_banner_pattern", () -> new BannerPatternItem(MarvelBannerPatterns.Tags.PATTERN_ITEM_HYDRA, new Item.Properties().stacksTo(1).rarity(Rarity.UNCOMMON)));
    public static final DeferredItem<Item> TESSERACT_SHARD = register("tesseract_shard", () -> new Item(new Item.Properties().rarity(Rarity.RARE)));
    public static final DeferredItem<Item> TESSERACT_CROSSBOW = register("tesseract_crossbow", () -> new TesseractCrossbowItem(new Item.Properties().rarity(Rarity.RARE).stacksTo(1).durability(930).component(DataComponents.CHARGED_PROJECTILES, ChargedProjectiles.EMPTY)));
    public static final DeferredItem<Item> WINTER_SOLDIER_KNIFE = register("winter_soldier_knife", () -> new SwordItem(Tiers.IRON, new Item.Properties().attributes(SwordItem.createAttributes(Tiers.IRON, 0, -1.8F))));
    public static final DeferredItem<Item> TESSERACT = register("tesseract", () -> new TesseractItem(MarvelBlocks.TESSERACT.get(), new Item.Properties().rarity(Rarity.EPIC).stacksTo(1)));
    public static final DeferredItem<Item> SPACE_STONE = register("space_stone", () -> new SpaceStoneItem(new Item.Properties().rarity(Rarity.EPIC).stacksTo(1)));
    public static final DeferredItem<Item> CAPTAIN_AMERICA_HELMET = register("captain_america_helmet", () -> new CaptainAmericaSuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33))));
    public static final DeferredItem<Item> CAPTAIN_AMERICA_CHESTPLATE = register("captain_america_chestplate", () -> new CaptainAmericaSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> CAPTAIN_AMERICA_LEGGINGS = register("captain_america_leggings", () -> new CaptainAmericaSuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> CAPTAIN_AMERICA_BOOTS = register("captain_america_boots", () -> new CaptainAmericaSuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> CAPTAIN_AMERICA_STEALTH_HELMET = register("captain_america_stealth_helmet", () -> new CaptainAmericaSuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33))));
    public static final DeferredItem<Item> CAPTAIN_AMERICA_STEALTH_CHESTPLATE = register("captain_america_stealth_chestplate", () -> new CaptainAmericaSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> CAPTAIN_AMERICA_STEALTH_LEGGINGS = register("captain_america_stealth_leggings", () -> new CaptainAmericaSuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> CAPTAIN_AMERICA_STEALTH_BOOTS = register("captain_america_stealth_boots", () -> new CaptainAmericaSuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> CAPTAIN_CARTER_HELMET = register("captain_carter_helmet", () -> new CaptainCarterSuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33)).component(MarvelDataComponents.HELMET_OPEN, false)));
    public static final DeferredItem<Item> CAPTAIN_CARTER_CHESTPLATE = register("captain_carter_chestplate", () -> new CaptainAmericaSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> CAPTAIN_CARTER_LEGGINGS = register("captain_carter_leggings", () -> new CaptainAmericaSuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> CAPTAIN_CARTER_BOOTS = register("captain_carter_boots", () -> new CaptainAmericaSuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> RED_GUARDIAN_HELMET = register("red_guardian_helmet", () -> new CaptainAmericaSuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33))));
    public static final DeferredItem<Item> RED_GUARDIAN_CHESTPLATE = register("red_guardian_chestplate", () -> new CaptainAmericaSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> RED_GUARDIAN_LEGGINGS = register("red_guardian_leggings", () -> new CaptainAmericaSuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> RED_GUARDIAN_BOOTS = register("red_guardian_boots", () -> new CaptainAmericaSuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> VIBRANIUM_SHIELD = register("vibranium_shield", () -> new VibraniumShieldItem(VIBRANIUM_INGOT, new Item.Properties().rarity(Rarity.UNCOMMON).durability(4063).attributes(VibraniumShieldItem.vibraniumAttributes()).fireResistant()));
    public static final DeferredItem<Item> PROTO_ADAMANTIUM_SHIELD = register("proto_adamantium_shield", () -> new VibraniumShieldItem(VIBRANIUM_INGOT, new Item.Properties().rarity(Rarity.UNCOMMON).stacksTo(1).attributes(VibraniumShieldItem.protoAdamantiumAttributes()).fireResistant()));
    public static final DeferredItem<Item> BLACK_PANTHER_HELMET = register("black_panther_helmet", () -> new BlackPantherSuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(45))));
    public static final DeferredItem<Item> BLACK_PANTHER_CHESTPLATE = register("black_panther_chestplate", () -> new BlackPantherSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(45))));
    public static final DeferredItem<Item> BLACK_PANTHER_LEGGINGS = register("black_panther_leggings", () -> new BlackPantherSuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(45))));
    public static final DeferredItem<Item> BLACK_PANTHER_BOOTS = register("black_panther_boots", () -> new BlackPantherSuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(45))));
    public static final DeferredItem<Item> KINETIC_BLACK_PANTHER_HELMET = register("kinetic_black_panther_helmet", () -> new KineticBlackPantherSuitItem(0x8A5DEB, ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(45)).component(MarvelDataComponents.HELMET_OPEN, false)));
    public static final DeferredItem<Item> KINETIC_BLACK_PANTHER_CHESTPLATE = register("kinetic_black_panther_chestplate", () -> new KineticBlackPantherSuitItem(0x8A5DEB, ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(45))));
    public static final DeferredItem<Item> KINETIC_BLACK_PANTHER_LEGGINGS = register("kinetic_black_panther_leggings", () -> new KineticBlackPantherSuitItem(0x8A5DEB, ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(45))));
    public static final DeferredItem<Item> KINETIC_BLACK_PANTHER_BOOTS = register("kinetic_black_panther_boots", () -> new KineticBlackPantherSuitItem(0x8A5DEB, ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(45))));
    public static final DeferredItem<Item> KINETIC_BLACK_PANTHER_NECKLACE = register("kinetic_black_panther_necklace", () -> new KineticBlackPantherNecklaceItem(0x8A5DEB, List.of(KINETIC_BLACK_PANTHER_BOOTS, KINETIC_BLACK_PANTHER_LEGGINGS, KINETIC_BLACK_PANTHER_CHESTPLATE, KINETIC_BLACK_PANTHER_HELMET), new Item.Properties()));
    public static final DeferredItem<Item> KILLMONGER_HELMET = register("killmonger_helmet", () -> new KineticBlackPantherSuitItem(0xFFC34C, ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(45)).component(MarvelDataComponents.HELMET_OPEN, false)));
    public static final DeferredItem<Item> KILLMONGER_CHESTPLATE = register("killmonger_chestplate", () -> new KineticBlackPantherSuitItem(0xFFC34C, ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(45))));
    public static final DeferredItem<Item> KILLMONGER_LEGGINGS = register("killmonger_leggings", () -> new KineticBlackPantherSuitItem(0xFFC34C, ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(45))));
    public static final DeferredItem<Item> KILLMONGER_BOOTS = register("killmonger_boots", () -> new KineticBlackPantherSuitItem(0xFFC34C, ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(45))));
    public static final DeferredItem<Item> KILLMONGER_NECKLACE = register("killmonger_necklace", () -> new KineticBlackPantherNecklaceItem(0xFFC34C, List.of(KILLMONGER_BOOTS, KILLMONGER_LEGGINGS, KILLMONGER_CHESTPLATE, KILLMONGER_HELMET), new Item.Properties()));
    public static final DeferredItem<Item> BLACK_PANTHER_SHURI_HELMET = register("black_panther_shuri_helmet", () -> new KineticBlackPantherSuitItem(0x8A5DEB, ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(45)).component(MarvelDataComponents.HELMET_OPEN, false)));
    public static final DeferredItem<Item> BLACK_PANTHER_SHURI_CHESTPLATE = register("black_panther_shuri_chestplate", () -> new KineticBlackPantherSuitItem(0x8A5DEB, ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(45))));
    public static final DeferredItem<Item> BLACK_PANTHER_SHURI_LEGGINGS = register("black_panther_shuri_leggings", () -> new KineticBlackPantherSuitItem(0x8A5DEB, ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(45))));
    public static final DeferredItem<Item> BLACK_PANTHER_SHURI_BOOTS = register("black_panther_shuri_boots", () -> new KineticBlackPantherSuitItem(0x8A5DEB, ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(45))));
    public static final DeferredItem<Item> BLACK_PANTHER_SHURI_NECKLACE = register("black_panther_shuri_necklace", () -> new KineticBlackPantherNecklaceItem(0x8A5DEB, List.of(BLACK_PANTHER_SHURI_BOOTS, BLACK_PANTHER_SHURI_LEGGINGS, BLACK_PANTHER_SHURI_CHESTPLATE, BLACK_PANTHER_SHURI_HELMET), new Item.Properties()));
    public static final DeferredItem<Item> ADAMANTIUM_CLAWS = register("adamantium_claws", () -> new AdamantiumClawsItem(new Item.Properties()));
    public static final DeferredItem<Item> WOLVERINE_HELMET = register("wolverine_helmet", () -> new WolverineSuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33))));
    public static final DeferredItem<Item> WOLVERINE_CHESTPLATE = register("wolverine_chestplate", () -> new WolverineSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> WOLVERINE_SLEEVELESS_CHESTPLATE = register("wolverine_sleeveless_chestplate", () -> new WolverineSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> WOLVERINE_LEGGINGS = register("wolverine_leggings", () -> new WolverineSuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> WOLVERINE_BOOTS = register("wolverine_boots", () -> new WolverineSuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> WOLVERINE_BROWN_HELMET = register("wolverine_brown_helmet", () -> new WolverineSuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33))));
    public static final DeferredItem<Item> WOLVERINE_BROWN_CHESTPLATE = register("wolverine_brown_chestplate", () -> new WolverineSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> WOLVERINE_BROWN_SLEEVELESS_CHESTPLATE = register("wolverine_brown_sleeveless_chestplate", () -> new WolverineSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> WOLVERINE_BROWN_LEGGINGS = register("wolverine_brown_leggings", () -> new WolverineSuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> WOLVERINE_BROWN_BOOTS = register("wolverine_brown_boots", () -> new WolverineSuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> WOLVERINE_X_FORCE_HELMET = register("wolverine_x_force_helmet", () -> new WolverineSuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33))));
    public static final DeferredItem<Item> WOLVERINE_X_FORCE_CHESTPLATE = register("wolverine_x_force_chestplate", () -> new WolverineSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> WOLVERINE_X_FORCE_SLEEVELESS_CHESTPLATE = register("wolverine_x_force_sleeveless_chestplate", () -> new WolverineSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> WOLVERINE_X_FORCE_LEGGINGS = register("wolverine_x_force_leggings", () -> new WolverineSuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> WOLVERINE_X_FORCE_BOOTS = register("wolverine_x_force_boots", () -> new WolverineSuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> OPTIC_BLAST = register("optic_blast", () -> new OpticBlastItem(new Item.Properties()));
    public static final DeferredItem<Item> CYCLOPS_HELMET = register("cyclops_helmet", () -> new CyclopsSuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33))));
    public static final DeferredItem<Item> CYCLOPS_CHESTPLATE = register("cyclops_chestplate", () -> new CyclopsSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> CYCLOPS_LEGGINGS = register("cyclops_leggings", () -> new CyclopsSuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> CYCLOPS_BOOTS = register("cyclops_boots", () -> new CyclopsSuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> CYCLOPS_ASTONISHING_HELMET = register("cyclops_astonishing_helmet", () -> new CyclopsSuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33))));
    public static final DeferredItem<Item> CYCLOPS_ASTONISHING_CHESTPLATE = register("cyclops_astonishing_chestplate", () -> new CyclopsSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> CYCLOPS_ASTONISHING_LEGGINGS = register("cyclops_astonishing_leggings", () -> new CyclopsSuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> CYCLOPS_ASTONISHING_BOOTS = register("cyclops_astonishing_boots", () -> new CyclopsSuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> WEB_SHOOTER = register("web_shooter", () -> new WebShooterItem(new Item.Properties().stacksTo(1)));
    public static final DeferredItem<Item> WEB_FLUID = register("web_fluid", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> SPIDER_MAN_HELMET = register("spider_man_helmet", () -> new SpiderManSuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33))));
    public static final DeferredItem<Item> SPIDER_MAN_CHESTPLATE = register("spider_man_chestplate", () -> new SpiderManSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> SPIDER_MAN_LEGGINGS = register("spider_man_leggings", () -> new SpiderManSuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> SPIDER_MAN_BOOTS = register("spider_man_boots", () -> new SpiderManSuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> SPIDER_MAN_MCU_HELMET = register("spider_man_mcu_helmet", () -> new SpiderManSuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33))));
    public static final DeferredItem<Item> SPIDER_MAN_MCU_CHESTPLATE = register("spider_man_mcu_chestplate", () -> new SpiderManSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> SPIDER_MAN_MCU_LEGGINGS = register("spider_man_mcu_leggings", () -> new SpiderManSuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> SPIDER_MAN_MCU_BOOTS = register("spider_man_mcu_boots", () -> new SpiderManSuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> MILES_MORALES_HELMET = register("miles_morales_suit_helmet", () -> new SpiderManSuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33))));
    public static final DeferredItem<Item> MILES_MORALES_CHESTPLATE = register("miles_morales_suit_chestplate", () -> new SpiderManSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> MILES_MORALES_LEGGINGS = register("miles_morales_suit_leggings", () -> new SpiderManSuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> MILES_MORALES_BOOTS = register("miles_morales_suit_boots", () -> new SpiderManSuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> SPIDER_GWEN_HELMET = register("spider_gwen_helmet", () -> new SpiderManSuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33))));
    public static final DeferredItem<Item> SPIDER_GWEN_CHESTPLATE = register("spider_gwen_chestplate", () -> new SpiderManSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> SPIDER_GWEN_LEGGINGS = register("spider_gwen_leggings", () -> new SpiderManSuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> SPIDER_GWEN_BOOTS = register("spider_gwen_boots", () -> new SpiderManSuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> SPIDER_MAN_INSOMNIAC_HELMET = register("spider_man_insomniac_helmet", () -> new SpiderManSuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33))));
    public static final DeferredItem<Item> SPIDER_MAN_INSOMNIAC_CHESTPLATE = register("spider_man_insomniac_chestplate", () -> new SpiderManSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> SPIDER_MAN_INSOMNIAC_LEGGINGS = register("spider_man_insomniac_leggings", () -> new SpiderManSuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> SPIDER_MAN_INSOMNIAC_BOOTS = register("spider_man_insomniac_boots", () -> new SpiderManSuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> SHRINK = register("shrink", () -> new SizeItem(Size.SMALL, new Item.Properties().stacksTo(1)));
    public static final DeferredItem<Item> GROW = register("grow", () -> new SizeItem(Size.BIG, new Item.Properties().stacksTo(1)));
    public static final DeferredItem<Item> ANT_MAN_HELMET = register("ant_man_helmet", () -> new AntManSuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33)).component(MarvelDataComponents.HELMET_OPEN, false)));
    public static final DeferredItem<Item> ANT_MAN_CHESTPLATE = register("ant_man_chestplate", () -> new AntManSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> ANT_MAN_LEGGINGS = register("ant_man_leggings", () -> new AntManSuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> ANT_MAN_BOOTS = register("ant_man_boots", () -> new AntManSuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> ANT_MAN_UPGRADED_HELMET = register("ant_man_upgraded_helmet", () -> new AntManUpgradedSuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33)).component(MarvelDataComponents.HELMET_OPEN, false)));
    public static final DeferredItem<Item> ANT_MAN_UPGRADED_CHESTPLATE = register("ant_man_upgraded_chestplate", () -> new AntManUpgradedSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> ANT_MAN_UPGRADED_LEGGINGS = register("ant_man_upgraded_leggings", () -> new AntManUpgradedSuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> ANT_MAN_UPGRADED_BOOTS = register("ant_man_upgraded_boots", () -> new AntManUpgradedSuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> STING = register("sting", () -> new WaspStingItem(new Item.Properties().stacksTo(1)));
    public static final DeferredItem<Item> WASP_HELMET = register("wasp_helmet", () -> new WaspSuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33)).component(MarvelDataComponents.HELMET_OPEN, false)));
    public static final DeferredItem<Item> WASP_CHESTPLATE = register("wasp_chestplate", () -> new WaspSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> WASP_LEGGINGS = register("wasp_leggings", () -> new WaspSuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> WASP_BOOTS = register("wasp_boots", () -> new WaspSuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> MJOLNIR = register("mjolnir", () -> new MjolnirItem(new Item.Properties().rarity(Rarity.RARE).stacksTo(1).attributes(MjolnirItem.attributes()).fireResistant()));
    public static final DeferredItem<Item> STORMBREAKER = register("stormbreaker", () -> new StormbreakerItem(new Item.Properties().rarity(Rarity.RARE).stacksTo(1).attributes(StormbreakerItem.attributes()).fireResistant()));
    public static final DeferredItem<Item> THOR_HELMET = register("thor_helmet", () -> new ThorSuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33)).component(MarvelDataComponents.HELMET_OPEN, false)));
    public static final DeferredItem<Item> THOR_CHESTPLATE = register("thor_chestplate", () -> new ThorSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> THOR_LEGGINGS = register("thor_leggings", () -> new ThorSuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> THOR_BOOTS = register("thor_boots", () -> new ThorSuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> PALLADIUM_ARC_REACTOR = register("palladium_arc_reactor", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> DIAMOND_ARC_REACTOR = register("diamond_arc_reactor", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> FLAMETHROWER = register("flamethrower", () -> new FlamethrowerItem(new Item.Properties().stacksTo(1)));
    public static final DeferredItem<Item> IRON_MAN_MARK_1_HELMET = register("iron_man_mark_1_helmet", () -> new IronManMark1SuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(15))));
    public static final DeferredItem<Item> IRON_MAN_MARK_1_CHESTPLATE = register("iron_man_mark_1_chestplate", () -> new IronManMark1SuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(15))));
    public static final DeferredItem<Item> IRON_MAN_MARK_1_LEGGINGS = register("iron_man_mark_1_leggings", () -> new IronManMark1SuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(15))));
    public static final DeferredItem<Item> IRON_MAN_MARK_1_BOOTS = register("iron_man_mark_1_boots", () -> new IronManMark1SuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(15))));
    public static final DeferredItem<Item> REPULSOR = register("repulsor", () -> new RepulsorItem(new Item.Properties().stacksTo(1)));
    public static final DeferredItem<Item> IRON_MAN_MARK_2_HELMET = register("iron_man_mark_2_helmet", () -> new IronManMark2SuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(25)).component(MarvelDataComponents.HELMET_OPEN, false)));
    public static final DeferredItem<Item> IRON_MAN_MARK_2_CHESTPLATE = register("iron_man_mark_2_chestplate", () -> new IronManMark2SuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(25))));
    public static final DeferredItem<Item> IRON_MAN_MARK_2_LEGGINGS = register("iron_man_mark_2_leggings", () -> new IronManMark2SuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(25))));
    public static final DeferredItem<Item> IRON_MAN_MARK_2_BOOTS = register("iron_man_mark_2_boots", () -> new IronManMark2SuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(25))));
    public static final DeferredItem<Item> UNIBEAM = register("unibeam", () -> new UnibeamItem(new Item.Properties().stacksTo(1)));
    public static final DeferredItem<Item> IRON_MAN_MARK_3_HELMET = register("iron_man_mark_3_helmet", () -> new IronManMark3SuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(25)).component(MarvelDataComponents.HELMET_OPEN, false)));
    public static final DeferredItem<Item> IRON_MAN_MARK_3_CHESTPLATE = register("iron_man_mark_3_chestplate", () -> new IronManMark3SuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(25))));
    public static final DeferredItem<Item> IRON_MAN_MARK_3_LEGGINGS = register("iron_man_mark_3_leggings", () -> new IronManMark3SuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(25))));
    public static final DeferredItem<Item> IRON_MAN_MARK_3_BOOTS = register("iron_man_mark_3_boots", () -> new IronManMark3SuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(25))));
    public static final DeferredItem<Item> IRON_MAN_MARK_5_HELMET = register("iron_man_mark_5_helmet", () -> new IronManMark5SuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(25)).component(MarvelDataComponents.HELMET_OPEN, false)));
    public static final DeferredItem<Item> IRON_MAN_MARK_5_CHESTPLATE = register("iron_man_mark_5_chestplate", () -> new IronManMark5SuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(25))));
    public static final DeferredItem<Item> IRON_MAN_MARK_5_LEGGINGS = register("iron_man_mark_5_leggings", () -> new IronManMark5SuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(25))));
    public static final DeferredItem<Item> IRON_MAN_MARK_5_BOOTS = register("iron_man_mark_5_boots", () -> new IronManMark5SuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(25))));
    public static final DeferredItem<Item> IRON_MAN_MARK_5_SUITCASE = register("iron_man_mark_5_suitcase", () -> new IronManMark5SuitcaseItem(new Item.Properties()));
    public static final DeferredItem<Item> IRON_MAN_MARK_6_HELMET = register("iron_man_mark_6_helmet", () -> new IronManMark6SuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(25)).component(MarvelDataComponents.HELMET_OPEN, false)));
    public static final DeferredItem<Item> IRON_MAN_MARK_6_CHESTPLATE = register("iron_man_mark_6_chestplate", () -> new IronManMark6SuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(25))));
    public static final DeferredItem<Item> IRON_MAN_MARK_6_LEGGINGS = register("iron_man_mark_6_leggings", () -> new IronManMark6SuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(25))));
    public static final DeferredItem<Item> IRON_MAN_MARK_6_BOOTS = register("iron_man_mark_6_boots", () -> new IronManMark6SuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(25))));
    public static final DeferredItem<Item> IRON_MAN_MARK_7_HELMET = register("iron_man_mark_7_helmet", () -> new IronManMark7SuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33)).component(MarvelDataComponents.HELMET_OPEN, false)));
    public static final DeferredItem<Item> IRON_MAN_MARK_7_CHESTPLATE = register("iron_man_mark_7_chestplate", () -> new IronManMark7SuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> IRON_MAN_MARK_7_LEGGINGS = register("iron_man_mark_7_leggings", () -> new IronManMark7SuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> IRON_MAN_MARK_7_BOOTS = register("iron_man_mark_7_boots", () -> new IronManMark7SuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> VERONICA_SATELLITE = register("veronica_satellite", () -> new VeronicaSatelliteItem(new Item.Properties().stacksTo(1)));
    public static final DeferredItem<Item> VERONICA_REMOTE = register("veronica_remote", () -> new VeronicaRemoteItem(new Item.Properties().stacksTo(1)));
    public static final DeferredItem<Item> IRON_MAN_MARK_11_HELMET = register("iron_man_mark_11_helmet", () -> new IronManMark11SuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33)).component(MarvelDataComponents.HELMET_OPEN, false)));
    public static final DeferredItem<Item> IRON_MAN_MARK_11_CHESTPLATE = register("iron_man_mark_11_chestplate", () -> new IronManMark11SuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> IRON_MAN_MARK_11_LEGGINGS = register("iron_man_mark_11_leggings", () -> new IronManMark11SuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> IRON_MAN_MARK_11_BOOTS = register("iron_man_mark_11_boots", () -> new IronManMark11SuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> IRON_MAN_MARK_15_HELMET = register("iron_man_mark_15_helmet", () -> new IronManMark15SuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33)).component(MarvelDataComponents.HELMET_OPEN, false)));
    public static final DeferredItem<Item> IRON_MAN_MARK_15_CHESTPLATE = register("iron_man_mark_15_chestplate", () -> new IronManMark15SuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> IRON_MAN_MARK_15_LEGGINGS = register("iron_man_mark_15_leggings", () -> new IronManMark15SuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> IRON_MAN_MARK_15_BOOTS = register("iron_man_mark_15_boots", () -> new IronManMark15SuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> IRON_MAN_MARK_17_HELMET = register("iron_man_mark_17_helmet", () -> new IronManMark17SuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33)).component(MarvelDataComponents.HELMET_OPEN, false)));
    public static final DeferredItem<Item> IRON_MAN_MARK_17_CHESTPLATE = register("iron_man_mark_17_chestplate", () -> new IronManMark17SuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> IRON_MAN_MARK_17_LEGGINGS = register("iron_man_mark_17_leggings", () -> new IronManMark17SuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> IRON_MAN_MARK_17_BOOTS = register("iron_man_mark_17_boots", () -> new IronManMark17SuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> IRON_MAN_MARK_19_HELMET = register("iron_man_mark_19_helmet", () -> new IronManMark19SuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33)).component(MarvelDataComponents.HELMET_OPEN, false)));
    public static final DeferredItem<Item> IRON_MAN_MARK_19_CHESTPLATE = register("iron_man_mark_19_chestplate", () -> new IronManMark19SuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> IRON_MAN_MARK_19_LEGGINGS = register("iron_man_mark_19_leggings", () -> new IronManMark19SuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> IRON_MAN_MARK_19_BOOTS = register("iron_man_mark_19_boots", () -> new IronManMark19SuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> IRON_MAN_MARK_20_HELMET = register("iron_man_mark_20_helmet", () -> new IronManMark20SuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33)).component(MarvelDataComponents.HELMET_OPEN, false)));
    public static final DeferredItem<Item> IRON_MAN_MARK_20_CHESTPLATE = register("iron_man_mark_20_chestplate", () -> new IronManMark20SuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> IRON_MAN_MARK_20_LEGGINGS = register("iron_man_mark_20_leggings", () -> new IronManMark20SuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> IRON_MAN_MARK_20_BOOTS = register("iron_man_mark_20_boots", () -> new IronManMark20SuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> IRON_MAN_MARK_21_HELMET = register("iron_man_mark_21_helmet", () -> new IronManMark21SuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33)).component(MarvelDataComponents.HELMET_OPEN, false)));
    public static final DeferredItem<Item> IRON_MAN_MARK_21_CHESTPLATE = register("iron_man_mark_21_chestplate", () -> new IronManMark21SuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> IRON_MAN_MARK_21_LEGGINGS = register("iron_man_mark_21_leggings", () -> new IronManMark21SuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> IRON_MAN_MARK_21_BOOTS = register("iron_man_mark_21_boots", () -> new IronManMark21SuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> SHOULDER_TURRET = register("shoulder_turret", () -> new ShoulderTurretItem(new Item.Properties().stacksTo(1)));
    public static final DeferredItem<Item> WAR_MACHINE_MARK_1_HELMET = register("war_machine_mark_1_helmet", () -> new WarMachineMark1SuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33)).component(MarvelDataComponents.HELMET_OPEN, false)));
    public static final DeferredItem<Item> WAR_MACHINE_MARK_1_CHESTPLATE = register("war_machine_mark_1_chestplate", () -> new WarMachineMark1SuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> WAR_MACHINE_MARK_1_LEGGINGS = register("war_machine_mark_1_leggings", () -> new WarMachineMark1SuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> WAR_MACHINE_MARK_1_BOOTS = register("war_machine_mark_1_boots", () -> new WarMachineMark1SuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> SONIC_BOOM = register("sonic_boom", () -> new SonicBoomItem(new Item.Properties().stacksTo(1)));
    public static final DeferredItem<Item> QUICKSILVER_CHESTPLATE = register("quicksilver_chestplate", () -> new QuicksilverSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> QUICKSILVER_LEGGINGS = register("quicksilver_leggings", () -> new QuicksilverSuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> QUICKSILVER_BOOTS = register("quicksilver_boots", () -> new QuicksilverSuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> QUICKSILVER_MCU_CHESTPLATE = register("quicksilver_mcu_chestplate", () -> new QuicksilverSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> QUICKSILVER_MCU_LEGGINGS = register("quicksilver_mcu_leggings", () -> new QuicksilverSuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> QUICKSILVER_MCU_BOOTS = register("quicksilver_mcu_boots", () -> new QuicksilverSuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> DEADPOOL_HELMET = register("deadpool_helmet", () -> new DeadpoolSuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33))));
    public static final DeferredItem<Item> DEADPOOL_CHESTPLATE = register("deadpool_chestplate", () -> new DeadpoolSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> DEADPOOL_LEGGINGS = register("deadpool_leggings", () -> new DeadpoolSuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> DEADPOOL_BOOTS = register("deadpool_boots", () -> new DeadpoolSuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> DEADPOOL_X_FORCE_HELMET = register("deadpool_x_force_helmet", () -> new DeadpoolSuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33))));
    public static final DeferredItem<Item> DEADPOOL_X_FORCE_CHESTPLATE = register("deadpool_x_force_chestplate", () -> new DeadpoolSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> DEADPOOL_X_FORCE_LEGGINGS = register("deadpool_x_force_leggings", () -> new DeadpoolSuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> DEADPOOL_X_FORCE_BOOTS = register("deadpool_x_force_boots", () -> new DeadpoolSuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> KATANAS = register("katanas", () -> new KatanasItem(new Item.Properties()));
    public static final DeferredItem<Item> KATANA_UPGRADE_SMITHING_TEMPLATE = register("katana_upgrade_smithing_template", KatanaUpgradeSmithingTemplateItem::new);
    public static final DeferredItem<Item> PHOTON_BLAST = register("photon_blast", () -> new PhotonBlastItem(new Item.Properties().stacksTo(1)));
    public static final DeferredItem<Item> CAPTAIN_MARVEL_HELMET = register("captain_marvel_helmet", () -> new CaptainMarvelSuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33)).component(MarvelDataComponents.HELMET_OPEN, false)));
    public static final DeferredItem<Item> CAPTAIN_MARVEL_CHESTPLATE = register("captain_marvel_chestplate", () -> new CaptainMarvelSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> CAPTAIN_MARVEL_LEGGINGS = register("captain_marvel_leggings", () -> new CaptainMarvelSuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> CAPTAIN_MARVEL_BOOTS = register("captain_marvel_boots", () -> new CaptainMarvelSuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> CAPTAIN_MARVEL_838_HELMET = register("captain_marvel_838_helmet", () -> new CaptainMarvel838SuitItem(ArmorItem.Type.HELMET, new Item.Properties().durability(ArmorItem.Type.HELMET.getDurability(33)).component(MarvelDataComponents.HELMET_OPEN, false)));
    public static final DeferredItem<Item> CAPTAIN_MARVEL_838_CHESTPLATE = register("captain_marvel_838_chestplate", () -> new CaptainMarvel838SuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> CAPTAIN_MARVEL_838_LEGGINGS = register("captain_marvel_838_leggings", () -> new CaptainMarvel838SuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> CAPTAIN_MARVEL_838_BOOTS = register("captain_marvel_838_boots", () -> new CaptainMarvel838SuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> WINTER_SOLDIER_CHESTPLATE = register("winter_soldier_chestplate", () -> new WinterSoldierSuitItem(ArmorItem.Type.CHESTPLATE, new Item.Properties().durability(ArmorItem.Type.CHESTPLATE.getDurability(33))));
    public static final DeferredItem<Item> WINTER_SOLDIER_LEGGINGS = register("winter_soldier_leggings", () -> new WinterSoldierSuitItem(ArmorItem.Type.LEGGINGS, new Item.Properties().durability(ArmorItem.Type.LEGGINGS.getDurability(33))));
    public static final DeferredItem<Item> WINTER_SOLDIER_BOOTS = register("winter_soldier_boots", () -> new WinterSoldierSuitItem(ArmorItem.Type.BOOTS, new Item.Properties().durability(ArmorItem.Type.BOOTS.getDurability(33))));
    public static final DeferredItem<Item> HYDRA_AGENT_SPAWN_EGG = register("hydra_agent_spawn_egg", () -> new DeferredSpawnEggItem(MarvelEntityTypes.HYDRA_AGENT, 0x399C23, 0xF6E32F, new Item.Properties()));
    public static final DeferredItem<Item> BARON_ZEMO_SPAWN_EGG = register("baron_zemo_spawn_egg", () -> new DeferredSpawnEggItem(MarvelEntityTypes.BARON_ZEMO, 0x59226E, 0xA92F97, new Item.Properties()));
    public static final DeferredItem<Item> WINTER_SOLDIER_SPAWN_EGG = register("winter_soldier_spawn_egg", () -> new DeferredSpawnEggItem(MarvelEntityTypes.WINTER_SOLDIER, 0x242321, 0xAEAEAE, new Item.Properties()));
    public static final DeferredItem<Item> RED_SKULL_SPAWN_EGG = register("red_skull_spawn_egg", () -> new DeferredSpawnEggItem(MarvelEntityTypes.RED_SKULL, 0x252724, 0xFF3030, new Item.Properties()));

    private static <T extends Item> DeferredItem<T> register(String id, Supplier<T> supplier) {
        return REGISTER.register(id, supplier);
    }

    @SubscribeEvent
    public static void brewingRecipe(RegisterBrewingRecipesEvent event) {
        event.getBuilder().addRecipe(Ingredient.of(UNSTABLE_PYM_PARTICLE), Ingredient.of(Items.NETHER_WART), PYM_PARTICLE.toStack(2));
        event.getBuilder().addRecipe(Ingredient.of(VILLAGER_BLOOD_SAMPLE), Ingredient.of(Items.NETHER_WART), X_GENES.toStack());
    }

    public static void register(IEventBus bus) {
        REGISTER.register(bus);
    }

    public static class Tags {
        public static final TagKey<Item> VIBRANIUM_ORES = create("vibranium_ores");
        public static final TagKey<Item> TITANIUM_ORES = create("titanium_ores");
        public static final TagKey<Item> PALLADIUM_ORES = create("palladium_ores");
        public static final TagKey<Item> SUIT_VARIANTS = create("suit_variants");
        public static final TagKey<Item> HIDES_OUTER_LAYER = create("hides_outer_layer");
        public static final TagKey<Item> INVISIBLE_WHEN_OPEN = create("invisible_when_open");
        public static final TagKey<Item> HAS_CAPE = create("has_cape");
        public static final TagKey<Item> SOUND_DAMPENING_BOOTS = create("sound_dampening_boots");
        public static final TagKey<Item> RENDER_HAND = create("render_hand");
        public static final TagKey<Item> FLYING_ARMOR = create("flying_armor");
        public static final TagKey<Item> CAPTAIN_AMERICA_ARMOR = create("captain_america_armor");
        public static final TagKey<Item> CAPTAIN_AMERICA_HELMET = create("captain_america_helmet");
        public static final TagKey<Item> CAPTAIN_AMERICA_CHESTPLATE = create("captain_america_chestplate");
        public static final TagKey<Item> CAPTAIN_AMERICA_LEGGINGS = create("captain_america_leggings");
        public static final TagKey<Item> CAPTAIN_AMERICA_BOOTS = create("captain_america_boots");
        public static final TagKey<Item> BLACK_PANTHER_ARMOR = create("black_panther_armor");
        public static final TagKey<Item> BLACK_PANTHER_HELMET = create("black_panther_helmet");
        public static final TagKey<Item> BLACK_PANTHER_CHESTPLATE = create("black_panther_chestplate");
        public static final TagKey<Item> BLACK_PANTHER_LEGGINGS = create("black_panther_leggings");
        public static final TagKey<Item> BLACK_PANTHER_BOOTS = create("black_panther_boots");
        public static final TagKey<Item> KINETIC_BLACK_PANTHER_ARMOR = create("kinetic_black_panther_armor");
        public static final TagKey<Item> KINETIC_BLACK_PANTHER_HELMET = create("kinetic_black_panther_helmet");
        public static final TagKey<Item> KINETIC_BLACK_PANTHER_CHESTPLATE = create("kinetic_black_panther_chestplate");
        public static final TagKey<Item> KINETIC_BLACK_PANTHER_LEGGINGS = create("kinetic_black_panther_leggings");
        public static final TagKey<Item> KINETIC_BLACK_PANTHER_BOOTS = create("kinetic_black_panther_boots");
        public static final TagKey<Item> WOLVERINE_ARMOR = create("wolverine_armor");
        public static final TagKey<Item> WOLVERINE_HELMET = create("wolverine_helmet");
        public static final TagKey<Item> WOLVERINE_CHESTPLATE = create("wolverine_chestplate");
        public static final TagKey<Item> WOLVERINE_LEGGINGS = create("wolverine_leggings");
        public static final TagKey<Item> WOLVERINE_BOOTS = create("wolverine_boots");
        public static final TagKey<Item> CYCLOPS_ARMOR = create("cyclops_armor");
        public static final TagKey<Item> CYCLOPS_HELMET = create("cyclops_helmet");
        public static final TagKey<Item> CYCLOPS_CHESTPLATE = create("cyclops_chestplate");
        public static final TagKey<Item> CYCLOPS_LEGGINGS = create("cyclops_leggings");
        public static final TagKey<Item> CYCLOPS_BOOTS = create("cyclops_boots");
        public static final TagKey<Item> SPIDER_MAN_ARMOR = create("spider_man_armor");
        public static final TagKey<Item> SPIDER_MAN_HELMET = create("spider_man_helmet");
        public static final TagKey<Item> SPIDER_MAN_CHESTPLATE = create("spider_man_chestplate");
        public static final TagKey<Item> SPIDER_MAN_LEGGINGS = create("spider_man_leggings");
        public static final TagKey<Item> SPIDER_MAN_BOOTS = create("spider_man_boots");
        public static final TagKey<Item> ANT_MAN_ARMOR = create("ant_man_armor");
        public static final TagKey<Item> ANT_MAN_HELMET = create("ant_man_helmet");
        public static final TagKey<Item> ANT_MAN_CHESTPLATE = create("ant_man_chestplate");
        public static final TagKey<Item> ANT_MAN_LEGGINGS = create("ant_man_leggings");
        public static final TagKey<Item> ANT_MAN_BOOTS = create("ant_man_boots");
        public static final TagKey<Item> ANT_MAN_UPGRADED_ARMOR = create("ant_man_upgraded_armor");
        public static final TagKey<Item> ANT_MAN_UPGRADED_HELMET = create("ant_man_upgraded_helmet");
        public static final TagKey<Item> ANT_MAN_UPGRADED_CHESTPLATE = create("ant_man_upgraded_chestplate");
        public static final TagKey<Item> ANT_MAN_UPGRADED_LEGGINGS = create("ant_man_upgraded_leggings");
        public static final TagKey<Item> ANT_MAN_UPGRADED_BOOTS = create("ant_man_upgraded_boots");
        public static final TagKey<Item> WASP_ARMOR = create("wasp_armor");
        public static final TagKey<Item> WASP_HELMET = create("wasp_helmet");
        public static final TagKey<Item> WASP_CHESTPLATE = create("wasp_chestplate");
        public static final TagKey<Item> WASP_LEGGINGS = create("wasp_leggings");
        public static final TagKey<Item> WASP_BOOTS = create("wasp_boots");
        public static final TagKey<Item> THOR_ARMOR = create("thor_armor");
        public static final TagKey<Item> THOR_HELMET = create("thor_helmet");
        public static final TagKey<Item> THOR_CHESTPLATE = create("thor_chestplate");
        public static final TagKey<Item> THOR_LEGGINGS = create("thor_leggings");
        public static final TagKey<Item> THOR_BOOTS = create("thor_boots");
        public static final TagKey<Item> IRON_MAN_MARK_1_ARMOR = create("iron_man_mark_1_armor");
        public static final TagKey<Item> IRON_MAN_MARK_1_HELMET = create("iron_man_mark_1_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_1_CHESTPLATE = create("iron_man_mark_1_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_1_LEGGINGS = create("iron_man_mark_1_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_1_BOOTS = create("iron_man_mark_1_boots");
        public static final TagKey<Item> IRON_MAN_MARK_2_ARMOR = create("iron_man_mark_2_armor");
        public static final TagKey<Item> IRON_MAN_MARK_2_HELMET = create("iron_man_mark_2_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_2_CHESTPLATE = create("iron_man_mark_2_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_2_LEGGINGS = create("iron_man_mark_2_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_2_BOOTS = create("iron_man_mark_2_boots");
        public static final TagKey<Item> IRON_MAN_MARK_3_ARMOR = create("iron_man_mark_3_armor");
        public static final TagKey<Item> IRON_MAN_MARK_3_HELMET = create("iron_man_mark_3_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_3_CHESTPLATE = create("iron_man_mark_3_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_3_LEGGINGS = create("iron_man_mark_3_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_3_BOOTS = create("iron_man_mark_3_boots");
        public static final TagKey<Item> IRON_MAN_MARK_5_ARMOR = create("iron_man_mark_5_armor");
        public static final TagKey<Item> IRON_MAN_MARK_5_HELMET = create("iron_man_mark_5_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_5_CHESTPLATE = create("iron_man_mark_5_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_5_LEGGINGS = create("iron_man_mark_5_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_5_BOOTS = create("iron_man_mark_5_boots");
        public static final TagKey<Item> IRON_MAN_MARK_6_ARMOR = create("iron_man_mark_6_armor");
        public static final TagKey<Item> IRON_MAN_MARK_6_HELMET = create("iron_man_mark_6_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_6_CHESTPLATE = create("iron_man_mark_6_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_6_LEGGINGS = create("iron_man_mark_6_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_6_BOOTS = create("iron_man_mark_6_boots");
        public static final TagKey<Item> IRON_MAN_MARK_7_ARMOR = create("iron_man_mark_7_armor");
        public static final TagKey<Item> IRON_MAN_MARK_7_HELMET = create("iron_man_mark_7_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_7_CHESTPLATE = create("iron_man_mark_7_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_7_LEGGINGS = create("iron_man_mark_7_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_7_BOOTS = create("iron_man_mark_7_boots");
        public static final TagKey<Item> IRON_MAN_MARK_11_ARMOR = create("iron_man_mark_11_armor");
        public static final TagKey<Item> IRON_MAN_MARK_11_HELMET = create("iron_man_mark_11_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_11_CHESTPLATE = create("iron_man_mark_11_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_11_LEGGINGS = create("iron_man_mark_11_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_11_BOOTS = create("iron_man_mark_11_boots");
        public static final TagKey<Item> IRON_MAN_MARK_15_ARMOR = create("iron_man_mark_15_armor");
        public static final TagKey<Item> IRON_MAN_MARK_15_HELMET = create("iron_man_mark_15_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_15_CHESTPLATE = create("iron_man_mark_15_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_15_LEGGINGS = create("iron_man_mark_15_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_15_BOOTS = create("iron_man_mark_15_boots");
        public static final TagKey<Item> IRON_MAN_MARK_17_ARMOR = create("iron_man_mark_17_armor");
        public static final TagKey<Item> IRON_MAN_MARK_17_HELMET = create("iron_man_mark_17_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_17_CHESTPLATE = create("iron_man_mark_17_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_17_LEGGINGS = create("iron_man_mark_17_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_17_BOOTS = create("iron_man_mark_17_boots");
        public static final TagKey<Item> IRON_MAN_MARK_19_ARMOR = create("iron_man_mark_19_armor");
        public static final TagKey<Item> IRON_MAN_MARK_19_HELMET = create("iron_man_mark_19_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_19_CHESTPLATE = create("iron_man_mark_19_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_19_LEGGINGS = create("iron_man_mark_19_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_19_BOOTS = create("iron_man_mark_19_boots");
        public static final TagKey<Item> IRON_MAN_MARK_20_ARMOR = create("iron_man_mark_20_armor");
        public static final TagKey<Item> IRON_MAN_MARK_20_HELMET = create("iron_man_mark_20_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_20_CHESTPLATE = create("iron_man_mark_20_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_20_LEGGINGS = create("iron_man_mark_20_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_20_BOOTS = create("iron_man_mark_20_boots");
        public static final TagKey<Item> IRON_MAN_MARK_21_ARMOR = create("iron_man_mark_21_armor");
        public static final TagKey<Item> IRON_MAN_MARK_21_HELMET = create("iron_man_mark_21_helmet");
        public static final TagKey<Item> IRON_MAN_MARK_21_CHESTPLATE = create("iron_man_mark_21_chestplate");
        public static final TagKey<Item> IRON_MAN_MARK_21_LEGGINGS = create("iron_man_mark_21_leggings");
        public static final TagKey<Item> IRON_MAN_MARK_21_BOOTS = create("iron_man_mark_21_boots");
        public static final TagKey<Item> WAR_MACHINE_MARK_1_ARMOR = create("war_machine_mark_1_armor");
        public static final TagKey<Item> WAR_MACHINE_MARK_1_HELMET = create("war_machine_mark_1_helmet");
        public static final TagKey<Item> WAR_MACHINE_MARK_1_CHESTPLATE = create("war_machine_mark_1_chestplate");
        public static final TagKey<Item> WAR_MACHINE_MARK_1_LEGGINGS = create("war_machine_mark_1_leggings");
        public static final TagKey<Item> WAR_MACHINE_MARK_1_BOOTS = create("war_machine_mark_1_boots");
        public static final TagKey<Item> IRON_MAN_ARMOR = create("iron_man_armor");
        public static final TagKey<Item> IRON_MAN_HELMET = create("iron_man_helmet");
        public static final TagKey<Item> IRON_MAN_CHESTPLATE = create("iron_man_chestplate");
        public static final TagKey<Item> IRON_MAN_LEGGINGS = create("iron_man_leggings");
        public static final TagKey<Item> IRON_MAN_BOOTS = create("iron_man_boots");
        public static final TagKey<Item> WAR_MACHINE_ARMOR = create("war_machine_armor");
        public static final TagKey<Item> WAR_MACHINE_HELMET = create("war_machine_helmet");
        public static final TagKey<Item> WAR_MACHINE_CHESTPLATE = create("war_machine_chestplate");
        public static final TagKey<Item> WAR_MACHINE_LEGGINGS = create("war_machine_leggings");
        public static final TagKey<Item> WAR_MACHINE_BOOTS = create("war_machine_boots");
        public static final TagKey<Item> QUICKSILVER_ARMOR = create("quicksilver_armor");
        public static final TagKey<Item> QUICKSILVER_CHESTPLATE = create("quicksilver_chestplate");
        public static final TagKey<Item> QUICKSILVER_LEGGINGS = create("quicksilver_leggings");
        public static final TagKey<Item> QUICKSILVER_BOOTS = create("quicksilver_boots");
        public static final TagKey<Item> DEADPOOL_ARMOR = create("deadpool_armor");
        public static final TagKey<Item> DEADPOOL_HELMET = create("deadpool_helmet");
        public static final TagKey<Item> DEADPOOL_CHESTPLATE = create("deadpool_chestplate");
        public static final TagKey<Item> DEADPOOL_LEGGINGS = create("deadpool_leggings");
        public static final TagKey<Item> DEADPOOL_BOOTS = create("deadpool_boots");
        public static final TagKey<Item> CAPTAIN_MARVEL_ARMOR = create("captain_marvel_armor");
        public static final TagKey<Item> CAPTAIN_MARVEL_HELMET = create("captain_marvel_helmet");
        public static final TagKey<Item> CAPTAIN_MARVEL_CHESTPLATE = create("captain_marvel_chestplate");
        public static final TagKey<Item> CAPTAIN_MARVEL_LEGGINGS = create("captain_marvel_leggings");
        public static final TagKey<Item> CAPTAIN_MARVEL_BOOTS = create("captain_marvel_boots");
        public static final TagKey<Item> WINTER_SOLDIER_ARMOR = create("winter_soldier_armor");
        public static final TagKey<Item> WINTER_SOLDIER_CHESTPLATE = create("winter_soldier_chestplate");
        public static final TagKey<Item> WINTER_SOLDIER_LEGGINGS = create("winter_soldier_leggings");
        public static final TagKey<Item> WINTER_SOLDIER_BOOTS = create("winter_soldier_boots");

        private static TagKey<Item> create(String id) {
            return REGISTER.createTagKey(id);
        }
    }
}
