modLoader="javafml"
loaderVersion="[37,)"
license="Public Domain"

[[mods]]
modId="marvel"
version="2.0-alpha.1"
displayName="Marvel Mod"
credits="R.I.P. Chadwick Boseman"
displayURL="https://www.curseforge.com/members/u1timatej7/projects"
authors="U1timateJ7, Alextimus9"

[[dependencies.marvel]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




