modLoader="javafml"
loaderVersion="[37,)"
license="Academic Free License v3.0"

[[mods]]
modId="marvel"
version="2.0-alpha.1"
displayName="Marvel Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://www.curseforge.com/members/u1timatej7/projects"
authors="U1timateJ7, Alextimus9"

[[dependencies.marvel]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




