
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package com.ulto.marvel.world.item;

import com.ulto.marvel.common.MarvelMod;
import com.ulto.marvel.world.level.block.MarvelModBlocks;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.TagKey;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import java.util.function.Supplier;

import static com.ulto.marvel.world.item.MarvelModTabs.*;
import static net.minecraft.world.item.CreativeModeTab.TAB_BUILDING_BLOCKS;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)
public class MarvelModItems {
	protected static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, MarvelMod.MOD_ID);

	protected static final Item.Properties defaultProperties = new Item.Properties().tab(TAB_MARVEL_ITEMS);
	protected static final Item.Properties nonStackableProperties = new Item.Properties().tab(TAB_MARVEL_ITEMS).stacksTo(1);
	protected static final Item.Properties weaponProperties = new Item.Properties().tab(TAB_MARVEL_WEAPONS).stacksTo(1);
	protected static final Item.Properties costumeProperties = new Item.Properties().tab(TAB_MARVEL_COSTUMES).stacksTo(1);
	protected static final Item.Properties ironManProperties = new Item.Properties().tab(TAB_IRON_MAN_ARMOR).stacksTo(1);
	protected static final Supplier<Item> defaultItem = () -> new Item(defaultProperties);
	protected static final Supplier<Item> fireproofItem = () -> new Item(new Item.Properties().tab(TAB_MARVEL_ITEMS).fireResistant());
	protected static final Supplier<Item> vibraniumItem = () -> new Item(new Item.Properties().tab(TAB_MARVEL_ITEMS).fireResistant().rarity(Rarity.UNCOMMON));

	static {
		REGISTRY.register(FMLJavaModLoadingContext.get().getModEventBus());
	}

	public static final RegistryObject<Item> HEART_SHAPED_HERB_FLOWER = block(MarvelModBlocks.HEART_SHAPED_HERB_FLOWER, TAB_MARVEL_ITEMS);
	public static final RegistryObject<Item> TITANIUM_ORE = block(MarvelModBlocks.TITANIUM_ORE, TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> DEEPSLATE_TITANIUM_ORE = block(MarvelModBlocks.DEEPSLATE_TITANIUM_ORE, TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> TITANIUM_BLOCK = block(MarvelModBlocks.TITANIUM_BLOCK, TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> RAW_TITANIUM_BLOCK = block(MarvelModBlocks.RAW_TITANIUM_BLOCK, TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> PALLADIUM_ORE = block(MarvelModBlocks.PALLADIUM_ORE, TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> DEEPSLATE_PALLADIUM_ORE = block(MarvelModBlocks.DEEPSLATE_PALLADIUM_ORE, TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> PALLADIUM_BLOCK = block(MarvelModBlocks.PALLADIUM_BLOCK, TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> RAW_PALLADIUM_BLOCK = block(MarvelModBlocks.RAW_PALLADIUM_BLOCK, TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> URU_ORE = block(MarvelModBlocks.URU_ORE, TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> DEEPSLATE_URU_ORE = block(MarvelModBlocks.DEEPSLATE_URU_ORE, TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> URU_BLOCK = block(MarvelModBlocks.URU_BLOCK, TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> RAW_URU_BLOCK = block(MarvelModBlocks.RAW_URU_BLOCK, TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> VIBRANIUM_ORE = block(MarvelModBlocks.VIBRANIUM_ORE, TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> DEEPSLATE_VIBRANIUM_ORE = block(MarvelModBlocks.DEEPSLATE_VIBRANIUM_ORE, TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> VIBRANIUM_BLOCK = block(MarvelModBlocks.VIBRANIUM_BLOCK, TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> ADAMANTIUM_BLOCK = block(MarvelModBlocks.ADAMANTIUM_BLOCK, TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> GOLD_TITANIUM_BLOCK = block(MarvelModBlocks.GOLD_TITANIUM_BLOCK, TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> IRON_MAN_SUIT_CHARGER = block(MarvelModBlocks.IRON_MAN_SUIT_CHARGER, TAB_MARVEL_ITEMS);
	public static final RegistryObject<Item> VIBRANIUM = REGISTRY.register("vibranium", vibraniumItem);
	public static final RegistryObject<Item> VIBRANIUM_INGOT = REGISTRY.register("vibranium_ingot", vibraniumItem);
	public static final RegistryObject<Item> URU_INGOT = REGISTRY.register("uru_ingot", defaultItem);
	public static final RegistryObject<Item> RAW_URU = REGISTRY.register("raw_uru", defaultItem);
	public static final RegistryObject<Item> TITANIUM_INGOT = REGISTRY.register("titanium_ingot", defaultItem);
	public static final RegistryObject<Item> RAW_TITANIUM = REGISTRY.register("raw_titanium", defaultItem);
	public static final RegistryObject<Item> ADAMANTIUM_INGOT = REGISTRY.register("adamantium_ingot", vibraniumItem);
	public static final RegistryObject<Item> PALLADIUM_INGOT = REGISTRY.register("palladium_ingot", defaultItem);
	public static final RegistryObject<Item> RAW_PALLADIUM = REGISTRY.register("raw_palladium", defaultItem);
	public static final RegistryObject<Item> GOLD_TITANIUM_ALLOY = REGISTRY.register("gold_titanium_alloy", defaultItem);
	public static final RegistryObject<Item> VIBRANIUM_WEAVE = REGISTRY.register("vibranium_weave", fireproofItem);
	public static final RegistryObject<Item> HEART_SHAPED_HERB_SEEDS = REGISTRY.register("heart_shaped_herb_seeds", () -> new ItemNameBlockItem(MarvelModBlocks.HEART_SHAPED_HERB_CROP.get(), (new Item.Properties()).tab(MarvelModTabs.TAB_MARVEL_ITEMS)));
	public static final RegistryObject<Item> HEART_SHAPED_HERB = REGISTRY.register("heart_shaped_herb", () -> new HeartShapedHerbItem(new Item.Properties().tab(MarvelModTabs.TAB_MARVEL_ITEMS).food((new FoodProperties.Builder()).nutrition(20).saturationMod(2f).alwaysEat().build())));
	public static final RegistryObject<Item> SUPER_SOLDIER_SERUM = REGISTRY.register("super_soldier_serum", () -> new SuperSoldierSerumItem(new Item.Properties().tab(MarvelModTabs.TAB_MARVEL_ITEMS).stacksTo(1).food((new FoodProperties.Builder()).nutrition(0).saturationMod(0f).alwaysEat().build())));
	public static final RegistryObject<Item> ANTI_SERUM = REGISTRY.register("anti_serum", () -> new AntiSerumItem(new Item.Properties().tab(MarvelModTabs.TAB_MARVEL_ITEMS).stacksTo(1).food((new FoodProperties.Builder()).nutrition(0).saturationMod(0f).alwaysEat().build())));
	public static final RegistryObject<Item> WEB_FLUID = REGISTRY.register("web_fluid", defaultItem);
	public static final RegistryObject<Item> PYM_PARTICLE = REGISTRY.register("pym_particle", defaultItem);
	public static final RegistryObject<Item> PALLADIUM_ARC_REACTOR = REGISTRY.register("palladium_arc_reactor", defaultItem);
	public static final RegistryObject<Item> UPGRADED_ARC_REACTOR = REGISTRY.register("upgraded_arc_reactor", defaultItem);
	public static final RegistryObject<Item> NEW_ELEMENT = REGISTRY.register("new_element", defaultItem);
	public static final RegistryObject<Item> BULLET = REGISTRY.register("bullet", defaultItem);
	public static final RegistryObject<Item> VERONICA_REMOTE = REGISTRY.register("veronica_remote", () -> new VeronicaRemoteItem(nonStackableProperties));
	public static final RegistryObject<Item> MARK_5_SUITCASE = REGISTRY.register("mark_5_suitcase", () -> new Mark5SuitcaseItem(nonStackableProperties));
	public static final RegistryObject<Item> MARK_50_ARC_REACTOR = REGISTRY.register("mark_50_arc_reactor", () -> new Mark50ArcReactorItem(defaultProperties));
	public static final RegistryObject<Item> MARK_85_ARC_REACTOR = REGISTRY.register("mark_85_arc_reactor", () -> new Mark85ArcReactorItem(defaultProperties));
	public static final RegistryObject<Item> IRON_SPIDER_STORAGE = REGISTRY.register("iron_spider_storage", () -> new IronSpiderStorageItem(defaultProperties));
	public static final RegistryObject<Item> MARK_47_GLASSES = REGISTRY.register("mark_47_glasses", () -> new Mark47GlassesItem(defaultProperties));
	public static final RegistryObject<Item> MJOLNIR = REGISTRY.register("mjolnir", () -> new MjolnirItem(weaponProperties));
	public static final RegistryObject<Item> STORMBREAKER = REGISTRY.register("stormbreaker", () -> new StormbreakerItem(weaponProperties));
	public static final RegistryObject<Item> WEB_SHOOTER_SWING = REGISTRY.register("web_shooter_swing", () -> new WebShooterSwingItem(weaponProperties));
	public static final RegistryObject<Item> VIBRANIUM_SHIELD = REGISTRY.register("vibranium_shield", () -> new VibraniumShieldItem(weaponProperties));
	public static final RegistryObject<Item> CAPTAIN_AMERICAS_SHIELD_RED = REGISTRY.register("captain_americas_shield_red", () -> new CapsShieldRedItem(weaponProperties));
	public static final RegistryObject<Item> CAPTAIN_AMERICAS_SHIELD_BLUE = REGISTRY.register("captain_americas_shield_blue", () -> new CapsShieldBlueItem(weaponProperties));
	public static final RegistryObject<Item> CAPTAIN_CARTERS_SHIELD = REGISTRY.register("captain_carters_shield", () -> new CaptainCartersShieldItem(weaponProperties));
	public static final RegistryObject<Item> US_AGENTS_SHIELD = REGISTRY.register("us_agents_shield", () -> new USAgentsShieldItem(weaponProperties));
	public static final RegistryObject<Item> RED_GUARDIAN_SHIELD = REGISTRY.register("red_guardian_shield", () -> new RedGuardianShieldItem(weaponProperties));
	public static final RegistryObject<Item> TASKMASTER_SHIELD = REGISTRY.register("taskmaster_shield", () -> new TaskmasterShieldItem(weaponProperties));
	public static final RegistryObject<Item> BLOODY_VIBRANIUM_SHIELD = REGISTRY.register("bloody_vibranium_shield", () -> new BloodyVibraniumShieldItem(weaponProperties));
	public static final RegistryObject<Item> BLOODY_CAPTAIN_AMERICAS_SHIELD_RED = REGISTRY.register("bloody_captain_americas_shield_red", () -> new BloodyCapsShieldRedItem(weaponProperties));
	public static final RegistryObject<Item> BLOODY_CAPTAIN_AMERICAS_SHIELD_BLUE = REGISTRY.register("bloody_captain_americas_shield_blue", () -> new BloodyCapsShieldBlueItem(weaponProperties));
	public static final RegistryObject<Item> BLOODY_CAPTAIN_CARTERS_SHIELD = REGISTRY.register("bloody_captain_carters_shield", () -> new BloodyCaptainCartersShieldItem(weaponProperties));
	public static final RegistryObject<Item> BLOODY_US_AGENTS_SHIELD = REGISTRY.register("bloody_us_agents_shield", () -> new BloodyUSAgentsShieldItem(weaponProperties));
	public static final RegistryObject<Item> BLOODY_RED_GUARDIAN_SHIELD = REGISTRY.register("bloody_red_guardian_shield", () -> new BloodyRedGuardianShieldItem(weaponProperties));
	public static final RegistryObject<Item> BLOODY_TASKMASTER_SHIELD = REGISTRY.register("bloody_taskmaster_shield", () -> new BloodyTaskmasterShieldItem(weaponProperties));
	public static final RegistryObject<Item> SHRINKING_DISK = REGISTRY.register("shrinking_disk", () -> new ShrinkingDiskItem(defaultProperties));
	public static final RegistryObject<Item> GROWING_DISK = REGISTRY.register("growing_disk", () -> new GrowingDiskItem(defaultProperties));
	public static final RegistryObject<Item> VIBRANIUM_SWORD = REGISTRY.register("vibranium_sword", () -> new SwordItem(MarvelModTiers.VIBRANIUM, 3, -2.4f, new Item.Properties().tab(CreativeModeTab.TAB_COMBAT).fireResistant()));
	public static final RegistryObject<Item> VIBRANIUM_SHOVEL = REGISTRY.register("vibranium_shovel", () -> new ShovelItem(MarvelModTiers.VIBRANIUM, 1.5f, -2.4f, new Item.Properties().tab(CreativeModeTab.TAB_TOOLS).fireResistant()));
	public static final RegistryObject<Item> VIBRANIUM_PICKAXE = REGISTRY.register("vibranium_pickaxe", () -> new PickaxeItem(MarvelModTiers.VIBRANIUM, 1, -2.8f, new Item.Properties().tab(CreativeModeTab.TAB_TOOLS).fireResistant()));
	public static final RegistryObject<Item> VIBRANIUM_AXE = REGISTRY.register("vibranium_axe", () -> new AxeItem(MarvelModTiers.VIBRANIUM, 5, -3f, new Item.Properties().tab(CreativeModeTab.TAB_TOOLS).fireResistant()));
	public static final RegistryObject<Item> VIBRANIUM_HOE = REGISTRY.register("vibranium_hoe", () -> new HoeItem(MarvelModTiers.VIBRANIUM, -4, 0f, new Item.Properties().tab(CreativeModeTab.TAB_TOOLS).fireResistant()));
	public static final RegistryObject<Item> VIBRANIUM_HELMET = REGISTRY.register("vibranium_helmet", () -> new ArmorItem(MarvelModArmorMaterials.VIBRANIUM, EquipmentSlot.HEAD, new Item.Properties().tab(CreativeModeTab.TAB_COMBAT).fireResistant()));
	public static final RegistryObject<Item> VIBRANIUM_CHESTPLATE = REGISTRY.register("vibranium_chestplate", () -> new ArmorItem(MarvelModArmorMaterials.VIBRANIUM, EquipmentSlot.CHEST, new Item.Properties().tab(CreativeModeTab.TAB_COMBAT).fireResistant()));
	public static final RegistryObject<Item> VIBRANIUM_LEGGINGS = REGISTRY.register("vibranium_leggings", () -> new ArmorItem(MarvelModArmorMaterials.VIBRANIUM, EquipmentSlot.LEGS, new Item.Properties().tab(CreativeModeTab.TAB_COMBAT).fireResistant()));
	public static final RegistryObject<Item> VIBRANIUM_BOOTS = REGISTRY.register("vibranium_boots", () -> new ArmorItem(MarvelModArmorMaterials.VIBRANIUM, EquipmentSlot.FEET, new Item.Properties().tab(CreativeModeTab.TAB_COMBAT).fireResistant()));
	public static final RegistryObject<Item> CAPTAIN_AMERICA_SUIT = REGISTRY.register("captain_america_suit", () -> new CaptainAmericaSuitItem.Suit(new Item.Properties()));
	public static final RegistryObject<Item> CAPTAIN_AMERICA_SUIT_HELMET = REGISTRY.register("captain_america_suit_helmet", () -> new CaptainAmericaSuitItem.Helmet(costumeProperties));
	public static final RegistryObject<Item> CAPTAIN_AMERICA_SUIT_CHESTPLATE = REGISTRY.register("captain_america_suit_chestplate", () -> new CaptainAmericaSuitItem.Chestplate(costumeProperties));
	public static final RegistryObject<Item> CAPTAIN_AMERICA_SUIT_LEGGINGS = REGISTRY.register("captain_america_suit_leggings", () -> new CaptainAmericaSuitItem.Leggings(costumeProperties));
	public static final RegistryObject<Item> CAPTAIN_AMERICA_SUIT_BOOTS = REGISTRY.register("captain_america_suit_boots", () -> new CaptainAmericaSuitItem.Boots(costumeProperties));
	public static final RegistryObject<Item> CAPTAIN_AMERICA_STEALTH_SUIT_HELMET = REGISTRY.register("captain_america_stealth_suit_helmet", () -> new CaptainAmericaStealthSuitItem.Helmet(costumeProperties));
	public static final RegistryObject<Item> CAPTAIN_AMERICA_STEALTH_SUIT_CHESTPLATE = REGISTRY.register("captain_america_stealth_suit_chestplate", () -> new CaptainAmericaStealthSuitItem.Chestplate(costumeProperties));
	public static final RegistryObject<Item> CAPTAIN_AMERICA_STEALTH_SUIT_LEGGINGS = REGISTRY.register("captain_america_stealth_suit_leggings", () -> new CaptainAmericaStealthSuitItem.Leggings(costumeProperties));
	public static final RegistryObject<Item> CAPTAIN_AMERICA_STEALTH_SUIT_BOOTS = REGISTRY.register("captain_america_stealth_suit_boots", () -> new CaptainAmericaStealthSuitItem.Boots(costumeProperties));
	public static final RegistryObject<Item> CAPTAIN_CARTER_SUIT_CHESTPLATE = REGISTRY.register("captain_carter_suit_chestplate", () -> new CaptainCarterSuitItem.Chestplate(costumeProperties));
	public static final RegistryObject<Item> CAPTAIN_CARTER_SUIT_LEGGINGS = REGISTRY.register("captain_carter_suit_leggings", () -> new CaptainCarterSuitItem.Leggings(costumeProperties));
	public static final RegistryObject<Item> CAPTAIN_CARTER_SUIT_BOOTS = REGISTRY.register("captain_carter_suit_boots", () -> new CaptainCarterSuitItem.Boots(costumeProperties));
	public static final RegistryObject<Item> JOHN_WALKER_SUIT_HELMET = REGISTRY.register("john_walker_suit_helmet", () -> new JohnWalkerSuitItem.Helmet(costumeProperties));
	public static final RegistryObject<Item> JOHN_WALKER_SUIT_CHESTPLATE = REGISTRY.register("john_walker_suit_chestplate", () -> new JohnWalkerSuitItem.Chestplate(costumeProperties));
	public static final RegistryObject<Item> JOHN_WALKER_SUIT_LEGGINGS = REGISTRY.register("john_walker_suit_leggings", () -> new JohnWalkerSuitItem.Leggings(costumeProperties));
	public static final RegistryObject<Item> JOHN_WALKER_SUIT_BOOTS = REGISTRY.register("john_walker_suit_boots", () -> new JohnWalkerSuitItem.Boots(costumeProperties));
	public static final RegistryObject<Item> US_AGENT_SUIT_HELMET = REGISTRY.register("us_agent_suit_helmet", () -> new USAgentSuitItem.Helmet(costumeProperties));
	public static final RegistryObject<Item> US_AGENT_SUIT_CHESTPLATE = REGISTRY.register("us_agent_suit_chestplate", () -> new USAgentSuitItem.Chestplate(costumeProperties));
	public static final RegistryObject<Item> US_AGENT_SUIT_LEGGINGS = REGISTRY.register("us_agent_suit_leggings", () -> new USAgentSuitItem.Leggings(costumeProperties));
	public static final RegistryObject<Item> US_AGENT_SUIT_BOOTS = REGISTRY.register("us_agent_suit_boots", () -> new USAgentSuitItem.Boots(costumeProperties));
	public static final RegistryObject<Item> RED_GUARDIAN_SUIT_HELMET = REGISTRY.register("red_guardian_suit_helmet", () -> new RedGuardianSuitItem.Helmet(costumeProperties));
	public static final RegistryObject<Item> RED_GUARDIAN_SUIT_CHESTPLATE = REGISTRY.register("red_guardian_suit_chestplate", () -> new RedGuardianSuitItem.Chestplate(costumeProperties));
	public static final RegistryObject<Item> RED_GUARDIAN_SUIT_LEGGINGS = REGISTRY.register("red_guardian_suit_leggings", () -> new RedGuardianSuitItem.Leggings(costumeProperties));
	public static final RegistryObject<Item> RED_GUARDIAN_SUIT_BOOTS = REGISTRY.register("red_guardian_suit_boots", () -> new RedGuardianSuitItem.Boots(costumeProperties));
	public static final RegistryObject<Item> BLACK_PANTHER_SUIT_HELMET = REGISTRY.register("black_panther_suit_helmet", () -> new BlackPantherSuitItem.Helmet(costumeProperties));
	public static final RegistryObject<Item> BLACK_PANTHER_SUIT_CHESTPLATE = REGISTRY.register("black_panther_suit_chestplate", () -> new BlackPantherSuitItem.Chestplate(costumeProperties));
	public static final RegistryObject<Item> BLACK_PANTHER_SUIT_LEGGINGS = REGISTRY.register("black_panther_suit_leggings", () -> new BlackPantherSuitItem.Leggings(costumeProperties));
	public static final RegistryObject<Item> BLACK_PANTHER_SUIT_BOOTS = REGISTRY.register("black_panther_suit_boots", () -> new BlackPantherSuitItem.Boots(costumeProperties));
	public static final RegistryObject<Item> SPIDER_MAN_SUIT_HELMET = REGISTRY.register("spider_man_suit_helmet", () -> new SpiderManSuitItem.Helmet(costumeProperties));
	public static final RegistryObject<Item> SPIDER_MAN_SUIT_CHESTPLATE = REGISTRY.register("spider_man_suit_chestplate", () -> new SpiderManSuitItem.Chestplate(costumeProperties));
	public static final RegistryObject<Item> SPIDER_MAN_SUIT_LEGGINGS = REGISTRY.register("spider_man_suit_leggings", () -> new SpiderManSuitItem.Leggings(costumeProperties));
	public static final RegistryObject<Item> SPIDER_MAN_SUIT_BOOTS = REGISTRY.register("spider_man_suit_boots", () -> new SpiderManSuitItem.Boots(costumeProperties));
	public static final RegistryObject<Item> IRON_SPIDER_SUIT_HELMET = REGISTRY.register("iron_spider_suit_helmet", () -> new IronSpiderSuitItem.Helmet(costumeProperties));
	public static final RegistryObject<Item> IRON_SPIDER_SUIT_CHESTPLATE = REGISTRY.register("iron_spider_suit_chestplate", () -> new IronSpiderSuitItem.Chestplate(costumeProperties));
	public static final RegistryObject<Item> IRON_SPIDER_SUIT_LEGGINGS = REGISTRY.register("iron_spider_suit_leggings", () -> new IronSpiderSuitItem.Leggings(costumeProperties));
	public static final RegistryObject<Item> IRON_SPIDER_SUIT_BOOTS = REGISTRY.register("iron_spider_suit_boots", () -> new IronSpiderSuitItem.Boots(costumeProperties));
	public static final RegistryObject<Item> WAR_MACHINE_HELMET = REGISTRY.register("war_machine_helmet", () -> new WarMachineItem.Helmet(costumeProperties));
	public static final RegistryObject<Item> WAR_MACHINE_CHESTPLATE = REGISTRY.register("war_machine_chestplate", () -> new WarMachineItem.Chestplate(costumeProperties));
	public static final RegistryObject<Item> WAR_MACHINE_LEGGINGS = REGISTRY.register("war_machine_leggings", () -> new WarMachineItem.Leggings(costumeProperties));
	public static final RegistryObject<Item> WAR_MACHINE_BOOTS = REGISTRY.register("war_machine_boots", () -> new WarMachineItem.Boots(costumeProperties));
	public static final RegistryObject<Item> IRON_PATRIOT_HELMET = REGISTRY.register("iron_patriot_helmet", () -> new IronPatriotItem.Helmet(costumeProperties));
	public static final RegistryObject<Item> IRON_PATRIOT_CHESTPLATE = REGISTRY.register("iron_patriot_chestplate", () -> new IronPatriotItem.Chestplate(costumeProperties));
	public static final RegistryObject<Item> IRON_PATRIOT_LEGGINGS = REGISTRY.register("iron_patriot_leggings", () -> new IronPatriotItem.Leggings(costumeProperties));
	public static final RegistryObject<Item> IRON_PATRIOT_BOOTS = REGISTRY.register("iron_patriot_boots", () -> new IronPatriotItem.Boots(costumeProperties));
	public static final RegistryObject<Item> WAR_MACHINE_MARK_2_HELMET = REGISTRY.register("war_machine_mark_2_helmet", () -> new WarMachineMark2Item.Helmet(costumeProperties));
	public static final RegistryObject<Item> WAR_MACHINE_MARK_2_CHESTPLATE = REGISTRY.register("war_machine_mark_2_chestplate", () -> new WarMachineMark2Item.Chestplate(costumeProperties));
	public static final RegistryObject<Item> WAR_MACHINE_MARK_2_LEGGINGS = REGISTRY.register("war_machine_mark_2_leggings", () -> new WarMachineMark2Item.Leggings(costumeProperties));
	public static final RegistryObject<Item> WAR_MACHINE_MARK_2_BOOTS = REGISTRY.register("war_machine_mark_2_boots", () -> new WarMachineMark2Item.Boots(costumeProperties));
	public static final RegistryObject<Item> ANTMAN_SUIT_HELMET = REGISTRY.register("antman_suit_helmet", () -> new AntmanSuitItem.Helmet(costumeProperties));
	public static final RegistryObject<Item> ANTMAN_SUIT_CHESTPLATE = REGISTRY.register("antman_suit_chestplate", () -> new AntmanSuitItem.Chestplate(costumeProperties));
	public static final RegistryObject<Item> ANTMAN_SUIT_LEGGINGS = REGISTRY.register("antman_suit_leggings", () -> new AntmanSuitItem.Leggings(costumeProperties));
	public static final RegistryObject<Item> ANTMAN_SUIT_BOOTS = REGISTRY.register("antman_suit_boots", () -> new AntmanSuitItem.Boots(costumeProperties));
	public static final RegistryObject<Item> ANTMAN_V2_SUIT_HELMET = REGISTRY.register("antman_v2_suit_helmet", () -> new AntmanV2SuitItem.Helmet(costumeProperties));
	public static final RegistryObject<Item> ANTMAN_V2_SUIT_CHESTPLATE = REGISTRY.register("antman_v2_suit_chestplate", () -> new AntmanV2SuitItem.Chestplate(costumeProperties));
	public static final RegistryObject<Item> ANTMAN_V2_SUIT_LEGGINGS = REGISTRY.register("antman_v2_suit_leggings", () -> new AntmanV2SuitItem.Leggings(costumeProperties));
	public static final RegistryObject<Item> ANTMAN_V2_SUIT_BOOTS = REGISTRY.register("antman_v2_suit_boots", () -> new AntmanV2SuitItem.Boots(costumeProperties));
	public static final RegistryObject<Item> WOLVERINE_SUIT_HELMET = REGISTRY.register("wolverine_suit_helmet", () -> new WolverineSuitItem.Helmet(costumeProperties));
	public static final RegistryObject<Item> WOLVERINE_SUIT_CHESTPLATE = REGISTRY.register("wolverine_suit_chestplate", () -> new WolverineSuitItem.Chestplate(costumeProperties));
	public static final RegistryObject<Item> WOLVERINE_SUIT_LEGGINGS = REGISTRY.register("wolverine_suit_leggings", () -> new WolverineSuitItem.Leggings(costumeProperties));
	public static final RegistryObject<Item> WOLVERINE_SUIT_BOOTS = REGISTRY.register("wolverine_suit_boots", () -> new WolverineSuitItem.Boots(costumeProperties));
	public static final RegistryObject<Item> QUICKSILVER_SUIT_CHESTPLATE = REGISTRY.register("quicksilver_suit_chestplate", () -> new QuicksilverSuitItem.Chestplate(costumeProperties));
	public static final RegistryObject<Item> QUICKSILVER_SUIT_LEGGINGS = REGISTRY.register("quicksilver_suit_leggings", () -> new QuicksilverSuitItem.Leggings(costumeProperties));
	public static final RegistryObject<Item> QUICKSILVER_SUIT_BOOTS = REGISTRY.register("quicksilver_suit_boots", () -> new QuicksilverSuitItem.Boots(costumeProperties));
	public static final RegistryObject<Item> TASKMASTER_SUIT_HELMET = REGISTRY.register("taskmaster_suit_helmet", () -> new TaskmasterSuitItem.Helmet(costumeProperties));
	public static final RegistryObject<Item> TASKMASTER_SUIT_CHESTPLATE = REGISTRY.register("taskmaster_suit_chestplate", () -> new TaskmasterSuitItem.Chestplate(costumeProperties));
	public static final RegistryObject<Item> TASKMASTER_SUIT_LEGGINGS = REGISTRY.register("taskmaster_suit_leggings", () -> new TaskmasterSuitItem.Leggings(costumeProperties));
	public static final RegistryObject<Item> TASKMASTER_SUIT_BOOTS = REGISTRY.register("taskmaster_suit_boots", () -> new TaskmasterSuitItem.Boots(costumeProperties));
	public static final RegistryObject<Item> REINFORCED_LEATHER = REGISTRY.register("reinforced_leather", () -> new Item(new Item.Properties().tab(CreativeModeTab.TAB_MISC)));
	public static final RegistryObject<Item> IRON_MAN_MARK_1_HELMET = REGISTRY.register("iron_man_mark_1_helmet", () -> new IronManMark1Item.Helmet(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_1_CHESTPLATE = REGISTRY.register("iron_man_mark_1_chestplate", () -> new IronManMark1Item.Chestplate(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_1_LEGGINGS = REGISTRY.register("iron_man_mark_1_leggings", () -> new IronManMark1Item.Leggings(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_1_BOOTS = REGISTRY.register("iron_man_mark_1_boots", () -> new IronManMark1Item.Boots(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_2_HELMET = REGISTRY.register("iron_man_mark_2_helmet", () -> new IronManMark2Item.Helmet(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_2_CHESTPLATE = REGISTRY.register("iron_man_mark_2_chestplate", () -> new IronManMark2Item.Chestplate(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_2_LEGGINGS = REGISTRY.register("iron_man_mark_2_leggings", () -> new IronManMark2Item.Leggings(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_2_BOOTS = REGISTRY.register("iron_man_mark_2_boots", () -> new IronManMark2Item.Boots(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_3_HELMET = REGISTRY.register("iron_man_mark_3_helmet", () -> new IronManMark3Item.Helmet(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_3_CHESTPLATE = REGISTRY.register("iron_man_mark_3_chestplate", () -> new IronManMark3Item.Chestplate(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_3_LEGGINGS = REGISTRY.register("iron_man_mark_3_leggings", () -> new IronManMark3Item.Leggings(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_3_BOOTS = REGISTRY.register("iron_man_mark_3_boots", () -> new IronManMark3Item.Boots(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_5_HELMET = REGISTRY.register("iron_man_mark_5_helmet", () -> new IronManMark5Item.Helmet(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_5_CHESTPLATE = REGISTRY.register("iron_man_mark_5_chestplate", () -> new IronManMark5Item.Chestplate(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_5_LEGGINGS = REGISTRY.register("iron_man_mark_5_leggings", () -> new IronManMark5Item.Leggings(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_5_BOOTS = REGISTRY.register("iron_man_mark_5_boots", () -> new IronManMark5Item.Boots(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_6_HELMET = REGISTRY.register("iron_man_mark_6_helmet", () -> new IronManMark6Item.Helmet(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_6_CHESTPLATE = REGISTRY.register("iron_man_mark_6_chestplate", () -> new IronManMark6Item.Chestplate(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_6_LEGGINGS = REGISTRY.register("iron_man_mark_6_leggings", () -> new IronManMark6Item.Leggings(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_6_BOOTS = REGISTRY.register("iron_man_mark_6_boots", () -> new IronManMark6Item.Boots(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_7_HELMET = REGISTRY.register("iron_man_mark_7_helmet", () -> new IronManMark7Item.Helmet(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_7_CHESTPLATE = REGISTRY.register("iron_man_mark_7_chestplate", () -> new IronManMark7Item.Chestplate(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_7_LEGGINGS = REGISTRY.register("iron_man_mark_7_leggings", () -> new IronManMark7Item.Leggings(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_7_BOOTS = REGISTRY.register("iron_man_mark_7_boots", () -> new IronManMark7Item.Boots(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_16_HELMET = REGISTRY.register("iron_man_mark_16_helmet", () -> new IronManMark16Item.Helmet(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_16_CHESTPLATE = REGISTRY.register("iron_man_mark_16_chestplate", () -> new IronManMark16Item.Chestplate(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_16_LEGGINGS = REGISTRY.register("iron_man_mark_16_leggings", () -> new IronManMark16Item.Leggings(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_16_BOOTS = REGISTRY.register("iron_man_mark_16_boots", () -> new IronManMark16Item.Boots(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_17_HELMET = REGISTRY.register("iron_man_mark_17_helmet", () -> new IronManMark17Item.Helmet(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_17_CHESTPLATE = REGISTRY.register("iron_man_mark_17_chestplate", () -> new IronManMark17Item.Chestplate(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_17_LEGGINGS = REGISTRY.register("iron_man_mark_17_leggings", () -> new IronManMark17Item.Leggings(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_17_BOOTS = REGISTRY.register("iron_man_mark_17_boots", () -> new IronManMark17Item.Boots(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_19_HELMET = REGISTRY.register("iron_man_mark_19_helmet", () -> new IronManMark19Item.Helmet(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_19_CHESTPLATE = REGISTRY.register("iron_man_mark_19_chestplate", () -> new IronManMark19Item.Chestplate(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_19_LEGGINGS = REGISTRY.register("iron_man_mark_19_leggings", () -> new IronManMark19Item.Leggings(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_19_BOOTS = REGISTRY.register("iron_man_mark_19_boots", () -> new IronManMark19Item.Boots(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_20_HELMET = REGISTRY.register("iron_man_mark_20_helmet", () -> new IronManMark20Item.Helmet(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_20_CHESTPLATE = REGISTRY.register("iron_man_mark_20_chestplate", () -> new IronManMark20Item.Chestplate(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_20_LEGGINGS = REGISTRY.register("iron_man_mark_20_leggings", () -> new IronManMark20Item.Leggings(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_20_BOOTS = REGISTRY.register("iron_man_mark_20_boots", () -> new IronManMark20Item.Boots(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_21_HELMET = REGISTRY.register("iron_man_mark_21_helmet", () -> new IronManMark21Item.Helmet(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_21_CHESTPLATE = REGISTRY.register("iron_man_mark_21_chestplate", () -> new IronManMark21Item.Chestplate(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_21_LEGGINGS = REGISTRY.register("iron_man_mark_21_leggings", () -> new IronManMark21Item.Leggings(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_21_BOOTS = REGISTRY.register("iron_man_mark_21_boots", () -> new IronManMark21Item.Boots(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_22_HELMET = REGISTRY.register("iron_man_mark_22_helmet", () -> new IronManMark22Item.Helmet(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_22_CHESTPLATE = REGISTRY.register("iron_man_mark_22_chestplate", () -> new IronManMark22Item.Chestplate(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_22_LEGGINGS = REGISTRY.register("iron_man_mark_22_leggings", () -> new IronManMark22Item.Leggings(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_22_BOOTS = REGISTRY.register("iron_man_mark_22_boots", () -> new IronManMark22Item.Boots(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_23_HELMET = REGISTRY.register("iron_man_mark_23_helmet", () -> new IronManMark23Item.Helmet(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_23_CHESTPLATE = REGISTRY.register("iron_man_mark_23_chestplate", () -> new IronManMark23Item.Chestplate(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_23_LEGGINGS = REGISTRY.register("iron_man_mark_23_leggings", () -> new IronManMark23Item.Leggings(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_23_BOOTS = REGISTRY.register("iron_man_mark_23_boots", () -> new IronManMark23Item.Boots(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_25_HELMET = REGISTRY.register("iron_man_mark_25_helmet", () -> new IronManMark25Item.Helmet(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_25_CHESTPLATE = REGISTRY.register("iron_man_mark_25_chestplate", () -> new IronManMark25Item.Chestplate(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_25_LEGGINGS = REGISTRY.register("iron_man_mark_25_leggings", () -> new IronManMark25Item.Leggings(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_25_BOOTS = REGISTRY.register("iron_man_mark_25_boots", () -> new IronManMark25Item.Boots(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_30_HELMET = REGISTRY.register("iron_man_mark_30_helmet", () -> new IronManMark30Item.Helmet(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_30_CHESTPLATE = REGISTRY.register("iron_man_mark_30_chestplate", () -> new IronManMark30Item.Chestplate(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_30_LEGGINGS = REGISTRY.register("iron_man_mark_30_leggings", () -> new IronManMark30Item.Leggings(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_30_BOOTS = REGISTRY.register("iron_man_mark_30_boots", () -> new IronManMark30Item.Boots(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_33_HELMET = REGISTRY.register("iron_man_mark_33_helmet", () -> new IronManMark33Item.Helmet(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_33_CHESTPLATE = REGISTRY.register("iron_man_mark_33_chestplate", () -> new IronManMark33Item.Chestplate(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_33_LEGGINGS = REGISTRY.register("iron_man_mark_33_leggings", () -> new IronManMark33Item.Leggings(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_33_BOOTS = REGISTRY.register("iron_man_mark_33_boots", () -> new IronManMark33Item.Boots(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_37_HELMET = REGISTRY.register("iron_man_mark_37_helmet", () -> new IronManMark37Item.Helmet(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_37_CHESTPLATE = REGISTRY.register("iron_man_mark_37_chestplate", () -> new IronManMark37Item.Chestplate(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_37_LEGGINGS = REGISTRY.register("iron_man_mark_37_leggings", () -> new IronManMark37Item.Leggings(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_37_BOOTS = REGISTRY.register("iron_man_mark_37_boots", () -> new IronManMark37Item.Boots(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_39_HELMET = REGISTRY.register("iron_man_mark_39_helmet", () -> new IronManMark39Item.Helmet(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_39_CHESTPLATE = REGISTRY.register("iron_man_mark_39_chestplate", () -> new IronManMark39Item.Chestplate(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_39_LEGGINGS = REGISTRY.register("iron_man_mark_39_leggings", () -> new IronManMark39Item.Leggings(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_39_BOOTS = REGISTRY.register("iron_man_mark_39_boots", () -> new IronManMark39Item.Boots(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_42_HELMET = REGISTRY.register("iron_man_mark_42_helmet", () -> new IronManMark42Item.Helmet(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_42_CHESTPLATE = REGISTRY.register("iron_man_mark_42_chestplate", () -> new IronManMark42Item.Chestplate(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_42_LEGGINGS = REGISTRY.register("iron_man_mark_42_leggings", () -> new IronManMark42Item.Leggings(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_42_BOOTS = REGISTRY.register("iron_man_mark_42_boots", () -> new IronManMark42Item.Boots(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_43_HELMET = REGISTRY.register("iron_man_mark_43_helmet", () -> new IronManMark43Item.Helmet(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_43_CHESTPLATE = REGISTRY.register("iron_man_mark_43_chestplate", () -> new IronManMark43Item.Chestplate(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_43_LEGGINGS = REGISTRY.register("iron_man_mark_43_leggings", () -> new IronManMark43Item.Leggings(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_43_BOOTS = REGISTRY.register("iron_man_mark_43_boots", () -> new IronManMark43Item.Boots(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_46_HELMET = REGISTRY.register("iron_man_mark_46_helmet", () -> new IronManMark46Item.Helmet(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_46_CHESTPLATE = REGISTRY.register("iron_man_mark_46_chestplate", () -> new IronManMark46Item.Chestplate(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_46_LEGGINGS = REGISTRY.register("iron_man_mark_46_leggings", () -> new IronManMark46Item.Leggings(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_46_BOOTS = REGISTRY.register("iron_man_mark_46_boots", () -> new IronManMark46Item.Boots(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_47_HELMET = REGISTRY.register("iron_man_mark_47_helmet", () -> new IronManMark47Item.Helmet(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_47_CHESTPLATE = REGISTRY.register("iron_man_mark_47_chestplate", () -> new IronManMark47Item.Chestplate(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_47_LEGGINGS = REGISTRY.register("iron_man_mark_47_leggings", () -> new IronManMark47Item.Leggings(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_47_BOOTS = REGISTRY.register("iron_man_mark_47_boots", () -> new IronManMark47Item.Boots(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_49_HELMET = REGISTRY.register("iron_man_mark_49_helmet", () -> new IronManMark49Item.Helmet(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_49_CHESTPLATE = REGISTRY.register("iron_man_mark_49_chestplate", () -> new IronManMark49Item.Chestplate(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_49_LEGGINGS = REGISTRY.register("iron_man_mark_49_leggings", () -> new IronManMark49Item.Leggings(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_49_BOOTS = REGISTRY.register("iron_man_mark_49_boots", () -> new IronManMark49Item.Boots(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_50_HELMET = REGISTRY.register("iron_man_mark_50_helmet", () -> new IronManMark50Item.Helmet(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_50_CHESTPLATE = REGISTRY.register("iron_man_mark_50_chestplate", () -> new IronManMark50Item.Chestplate(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_50_LEGGINGS = REGISTRY.register("iron_man_mark_50_leggings", () -> new IronManMark50Item.Leggings(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_50_BOOTS = REGISTRY.register("iron_man_mark_50_boots", () -> new IronManMark50Item.Boots(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_85_HELMET = REGISTRY.register("iron_man_mark_85_helmet", () -> new IronManMark85Item.Helmet(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_85_CHESTPLATE = REGISTRY.register("iron_man_mark_85_chestplate", () -> new IronManMark85Item.Chestplate(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_85_LEGGINGS = REGISTRY.register("iron_man_mark_85_leggings", () -> new IronManMark85Item.Leggings(ironManProperties));
	public static final RegistryObject<Item> IRON_MAN_MARK_85_BOOTS = REGISTRY.register("iron_man_mark_85_boots", () -> new IronManMark85Item.Boots(ironManProperties));
	public static final RegistryObject<Item> FLAME = REGISTRY.register("flame", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> FLAMETHROWER = REGISTRY.register("flamethrower", () -> new IronManFlamethrowerItem(new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> REPULSOR = REGISTRY.register("repulsor", () -> new RepulsorItem(new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> REPULSOR_BULLET = REGISTRY.register("repulsor_bullet", () -> new Item(new Item.Properties()));
	public static final RegistryObject<Item> UNIBEAM = REGISTRY.register("unibeam", () -> new UnibeamItem(new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> WAR_MACHINE_GUN = REGISTRY.register("war_machine_gun", () -> new WarMachineGunItem(new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> WEB_SHOOTER_TRAP = REGISTRY.register("web_shooter_trap", () -> new WebShooterTrapItem(new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> MARK_25_DRILL = REGISTRY.register("mark_25_drill", () -> new PickaxeItem(MarvelModTiers.DRILL, 4, -2.7f, new Item.Properties()));
	public static final RegistryObject<Item> CENTURION_BLADE = REGISTRY.register("centurion_blade", () -> new SwordItem(MarvelModTiers.BLADE, 3, -3f, new Item.Properties()));
	public static final RegistryObject<Item> SHRINK_ITEM = REGISTRY.register("shrink", () -> new ShrinkItemItem(new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> GROW_ITEM = REGISTRY.register("grow", () -> new GrowItemItem(new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> MARK_49_NANO_TOOL = REGISTRY.register("mark_49_nano_tool", () -> new Mark49NanoToolItem(new Item.Properties()));
	public static final RegistryObject<Item> MARK_50_NANO_TOOL = REGISTRY.register("mark_50_nano_tool", () -> new Mark50NanoToolItem(new Item.Properties()));
	public static final RegistryObject<Item> MARK_85_NANO_TOOL = REGISTRY.register("mark_85_nano_tool", () -> new Mark85NanoToolItem(new Item.Properties()));
	public static final RegistryObject<Item> ADAMANTIUM_CLAWS = REGISTRY.register("adamantium_claws", () -> new SwordItem(MarvelModTiers.CLAWS, 3, -2f, new Item.Properties()));
	public static final RegistryObject<Item> THOR_ARMOR_CHESTPLATE = REGISTRY.register("thor_armor_chestplate", () -> new ThorArmorItem.Chestplate(new Item.Properties()));
	public static final RegistryObject<Item> THOR_ARMOR_LEGGINGS = REGISTRY.register("thor_armor_leggings", () -> new ThorArmorItem.Leggings(new Item.Properties()));
	public static final RegistryObject<Item> THOR_ARMOR_BOOTS = REGISTRY.register("thor_armor_boots", () -> new ThorArmorItem.Boots(new Item.Properties()));
	public static final RegistryObject<Item> MARK_17_UNIBEAM = REGISTRY.register("mark_17_unibeam", () -> new Mark17UnibeamItem(new Item.Properties().stacksTo(1)));

	private static RegistryObject<Item> block(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(tab)));
	}

	public static class Tags {
		public static final TagKey<Item> FLYING_CHESTPLATES = REGISTRY.createTagKey(new ResourceLocation("forge:flying/chestplates"));
		public static final TagKey<Item> FLYING_BOOTS = REGISTRY.createTagKey(new ResourceLocation("forge:flying/boots"));
		public static final TagKey<Item> FLYING_HANDHELD = REGISTRY.createTagKey(new ResourceLocation("forge:flying/handheld"));
		public static final TagKey<Item> FLYING_HEIGHT_180 = REGISTRY.createTagKey(new ResourceLocation("forge:flying/height/180"));
		public static final TagKey<Item> FLYING_HEIGHT_200 = REGISTRY.createTagKey(new ResourceLocation("forge:flying/height/200"));
		public static final TagKey<Item> FLYING_HEIGHT_256 = REGISTRY.createTagKey(new ResourceLocation("forge:flying/height/256"));
		public static final TagKey<Item> FLYING_HEIGHT_384 = REGISTRY.createTagKey(new ResourceLocation("forge:flying/height/384"));

		public static final TagKey<Item> CLEAN_VIBRANIUM_SHIELDS = REGISTRY.createTagKey(new ResourceLocation(MarvelMod.MOD_ID, "clean_vibranium_shields"));
		public static final TagKey<Item> IRON_MAN_HELMETS = REGISTRY.createTagKey(new ResourceLocation(MarvelMod.MOD_ID, "iron_man_helmets"));
		public static final TagKey<Item> NANOTECH_HELMETS = REGISTRY.createTagKey(new ResourceLocation(MarvelMod.MOD_ID, "nanotech_helmets"));
		public static final TagKey<Item> PALLADIUM_ORES = REGISTRY.createTagKey(new ResourceLocation(MarvelMod.MOD_ID, "palladium_ores"));
		public static final TagKey<Item> SPIDER_MAN_ARMOR = REGISTRY.createTagKey(new ResourceLocation(MarvelMod.MOD_ID, "spider_man_armor"));
		public static final TagKey<Item> TITANIUM_ORES = REGISTRY.createTagKey(new ResourceLocation(MarvelMod.MOD_ID, "titanium_ores"));
		public static final TagKey<Item> URU_ORES = REGISTRY.createTagKey(new ResourceLocation(MarvelMod.MOD_ID, "uru_ores"));
		public static final TagKey<Item> VIBRANIUM_ORES = REGISTRY.createTagKey(new ResourceLocation(MarvelMod.MOD_ID, "vibranium_ores"));
		public static final TagKey<Item> VIBRANIUM_SHIELDS = REGISTRY.createTagKey(new ResourceLocation(MarvelMod.MOD_ID, "vibranium_shields"));
	}
}
