
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package com.ulto.marvel.init;

import com.ulto.marvel.item.*;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

import javax.annotation.Nullable;
import java.util.ArrayList;
import java.util.List;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)
public class MarvelModItems {
	private static final List<Item> REGISTRY = new ArrayList<>();
	public static final Item VIBRANIUM = register(new VibraniumItem());
	public static final Item VIBRANIUM_INGOT = register(new VibraniumIngotItem());
	public static final Item URU_INGOT = register(new UruIngotItem());
	public static final Item TITANIUM_INGOT = register(new TitaniumIngotItem());
	public static final Item ADAMANTIUM = register(new AdamantiumItem());
	public static final Item PALLADIUM_INGOT = register(new PalladiumIngotItem());
	public static final Item GOLD_TITANIUM_ALLOY = register(new GoldTitaniumAlloyItem());
	public static final Item VIBRANIUM_WEAVE = register(new VibraniumWeaveItem());
	public static final Item HEART_SHAPED_HERB = register(MarvelModBlocks.HEART_SHAPED_HERB, MarvelModTabs.TAB_MARVEL_ITEMS);
	public static final Item HEART_SHAPED_HERB_SEEDS = register(new HeartShapedHerbSeedsItem());
	public static final Item HEART_SHAPED_HERB_ITEM = register(new HeartShapedHerbItemItem());
	public static final Item SUPER_SOLDIER_SERUM = register(new SuperSoldierSerumItem());
	public static final Item ANTI_SERUM = register(new AntiSerumItem());
	public static final Item WEB_FLUID = register(new WebFluidItem());
	public static final Item PYM_PARTICLE = register(new PymParticleItem());
	public static final Item PALLADIUM_ARC_REACTOR = register(new PalladiumArcReactorItem());
	public static final Item UPGRADED_ARC_REACTOR = register(new UpgradedArcReactorItem());
	public static final Item NEW_ELEMENT = register(new NewElementItem());
	public static final Item BULLET = register(new BulletItem());
	public static final Item VERONICA_REMOTE = register(new VeronicaRemoteItem());
	public static final Item MARK_5_SUITCASE = register(new Mark5SuitcaseItem());
	public static final Item MARK_50_ARC_REACTOR_CHESTPLATE = register(new Mark50ArcReactorItem.Chestplate());
	public static final Item MARK_85_ARC_REACTOR_CHESTPLATE = register(new Mark85ArcReactorItem.Chestplate());
	public static final Item IRON_SPIDER_STORAGE_CHESTPLATE = register(new IronSpiderStorageItem.Chestplate());
	public static final Item MUTANT_GROWTH_HORMONE = register(new MutantGrowthHormoneItem());
	public static final Item MARK_47_GLASSES_HELMET = register(new Mark47GlassesItem.Helmet());
	public static final Item VIBRANIUM_ORE = register(MarvelModBlocks.VIBRANIUM_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final Item VIBRANIUM_BLOCK = register(MarvelModBlocks.VIBRANIUM_BLOCK, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final Item TITANIUM_ORE = register(MarvelModBlocks.TITANIUM_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final Item TITANIUM_BLOCK = register(MarvelModBlocks.TITANIUM_BLOCK, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final Item PALLADIUM_ORE = register(MarvelModBlocks.PALLADIUM_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final Item PALLADIUM_BLOCK = register(MarvelModBlocks.PALLADIUM_BLOCK, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final Item URU_ORE = register(MarvelModBlocks.URU_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final Item URU_BLOCK = register(MarvelModBlocks.URU_BLOCK, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final Item MJOLNIR = register(new MjolnirItem());
	public static final Item CAPTAIN_AMERICAS_SHIELD_RED = register(new CapsShieldRedItem());
	public static final Item STORMBREAKER = register(new StormbreakerItem());
	public static final Item WEB_SHOOTER_SWING = register(new WebShooterSwingItem());
	public static final Item VIBRANIUM_SHIELD = register(new VibraniumShieldItem());
	public static final Item CAPTAIN_AMERICAS_SHIELD_BLUE = register(new CapsShieldBlueItem());
	public static final Item RED_GUARDIAN_SHIELD = register(new RedGuardianShieldItem());
	public static final Item TASKMASTER_SHIELD = register(new TaskmasterShieldItem());
	public static final Item BLOODY_CAPTAIN_AMERICAS_SHIELD_RED = register(new BloodyCapsShieldRedItem());
	public static final Item BLOODY_VIBRANIUM_SHIELD = register(new BloodyVibraniumShieldItem());
	public static final Item BLOODY_CAPTAIN_AMERICAS_SHIELD_BLUE = register(new BloodyCapsShieldBlueItem());
	public static final Item BLOODY_RED_GUARDIAN_SHIELD = register(new BloodyRedGuardianShieldItem());
	public static final Item BLOODY_TASKMASTER_SHIELD = register(new BloodyTaskmasterShieldItem());
	public static final Item SHRINKING_DISK = register(new ShrinkingDiskItem());
	public static final Item GROWING_DISK = register(new GrowingDiskItem());
	public static final Item VIBRANIUM_SWORD = register(new VibraniumSwordItem());
	public static final Item VIBRANIUM_ARMOR_HELMET = register(new VibraniumArmorItem.Helmet());
	public static final Item VIBRANIUM_ARMOR_CHESTPLATE = register(new VibraniumArmorItem.Chestplate());
	public static final Item VIBRANIUM_ARMOR_LEGGINGS = register(new VibraniumArmorItem.Leggings());
	public static final Item VIBRANIUM_ARMOR_BOOTS = register(new VibraniumArmorItem.Boots());
	public static final Item VIBRANIUM_PICKAXE = register(new VibraniumPickaxeItem());
	public static final Item VIBRANIUM_AXE = register(new VibraniumAxeItem());
	public static final Item VIBRANIUM_SHOVEL = register(new VibraniumShovelItem());
	public static final Item VIBRANIUM_HOE = register(new VibraniumHoeItem());
	public static final Item CAPTAIN_AMERICA_SUIT_HELMET = register(new CaptainAmericaSuitItem.Helmet());
	public static final Item CAPTAIN_AMERICA_SUIT_CHESTPLATE = register(new CaptainAmericaSuitItem.Chestplate());
	public static final Item CAPTAIN_AMERICA_SUIT_LEGGINGS = register(new CaptainAmericaSuitItem.Leggings());
	public static final Item CAPTAIN_AMERICA_SUIT_BOOTS = register(new CaptainAmericaSuitItem.Boots());
	public static final Item CAPTAIN_AMERICA_STEALTH_SUIT_HELMET = register(new CaptainAmericaStealthSuitItem.Helmet());
	public static final Item CAPTAIN_AMERICA_STEALTH_SUIT_CHESTPLATE = register(new CaptainAmericaStealthSuitItem.Chestplate());
	public static final Item CAPTAIN_AMERICA_STEALTH_SUIT_LEGGINGS = register(new CaptainAmericaStealthSuitItem.Leggings());
	public static final Item CAPTAIN_AMERICA_STEALTH_SUIT_BOOTS = register(new CaptainAmericaStealthSuitItem.Boots());
	public static final Item JOHN_WALKER_SUIT_HELMET = register(new JohnWalkerSuitItem.Helmet());
	public static final Item JOHN_WALKER_SUIT_CHESTPLATE = register(new JohnWalkerSuitItem.Chestplate());
	public static final Item JOHN_WALKER_SUIT_LEGGINGS = register(new JohnWalkerSuitItem.Leggings());
	public static final Item JOHN_WALKER_SUIT_BOOTS = register(new JohnWalkerSuitItem.Boots());
	public static final Item BLACK_PANTHER_SUIT_HELMET = register(new BlackPantherSuitItem.Helmet());
	public static final Item BLACK_PANTHER_SUIT_CHESTPLATE = register(new BlackPantherSuitItem.Chestplate());
	public static final Item BLACK_PANTHER_SUIT_LEGGINGS = register(new BlackPantherSuitItem.Leggings());
	public static final Item BLACK_PANTHER_SUIT_BOOTS = register(new BlackPantherSuitItem.Boots());
	public static final Item SPIDER_MAN_SUIT_HELMET = register(new SpiderManSuitItem.Helmet());
	public static final Item SPIDER_MAN_SUIT_CHESTPLATE = register(new SpiderManSuitItem.Chestplate());
	public static final Item SPIDER_MAN_SUIT_LEGGINGS = register(new SpiderManSuitItem.Leggings());
	public static final Item SPIDER_MAN_SUIT_BOOTS = register(new SpiderManSuitItem.Boots());
	public static final Item IRON_SPIDER_SUIT_HELMET = register(new IronSpiderSuitItem.Helmet());
	public static final Item IRON_SPIDER_SUIT_CHESTPLATE = register(new IronSpiderSuitItem.Chestplate());
	public static final Item IRON_SPIDER_SUIT_LEGGINGS = register(new IronSpiderSuitItem.Leggings());
	public static final Item IRON_SPIDER_SUIT_BOOTS = register(new IronSpiderSuitItem.Boots());
	public static final Item WAR_MACHINE_HELMET = register(new WarMachineItem.Helmet());
	public static final Item WAR_MACHINE_CHESTPLATE = register(new WarMachineItem.Chestplate());
	public static final Item WAR_MACHINE_LEGGINGS = register(new WarMachineItem.Leggings());
	public static final Item WAR_MACHINE_BOOTS = register(new WarMachineItem.Boots());
	public static final Item IRON_PATRIOT_HELMET = register(new IronPatriotItem.Helmet());
	public static final Item IRON_PATRIOT_CHESTPLATE = register(new IronPatriotItem.Chestplate());
	public static final Item IRON_PATRIOT_LEGGINGS = register(new IronPatriotItem.Leggings());
	public static final Item IRON_PATRIOT_BOOTS = register(new IronPatriotItem.Boots());
	public static final Item WAR_MACHINE_MARK_2_HELMET = register(new WarMachineMark2Item.Helmet());
	public static final Item WAR_MACHINE_MARK_2_CHESTPLATE = register(new WarMachineMark2Item.Chestplate());
	public static final Item WAR_MACHINE_MARK_2_LEGGINGS = register(new WarMachineMark2Item.Leggings());
	public static final Item WAR_MACHINE_MARK_2_BOOTS = register(new WarMachineMark2Item.Boots());
	public static final Item RED_GUARDIAN_SUIT_HELMET = register(new RedGuardianSuitItem.Helmet());
	public static final Item RED_GUARDIAN_SUIT_CHESTPLATE = register(new RedGuardianSuitItem.Chestplate());
	public static final Item RED_GUARDIAN_SUIT_LEGGINGS = register(new RedGuardianSuitItem.Leggings());
	public static final Item RED_GUARDIAN_SUIT_BOOTS = register(new RedGuardianSuitItem.Boots());
	public static final Item ANTMAN_SUIT_HELMET = register(new AntmanSuitItem.Helmet());
	public static final Item ANTMAN_SUIT_CHESTPLATE = register(new AntmanSuitItem.Chestplate());
	public static final Item ANTMAN_SUIT_LEGGINGS = register(new AntmanSuitItem.Leggings());
	public static final Item ANTMAN_SUIT_BOOTS = register(new AntmanSuitItem.Boots());
	public static final Item ANTMAN_V_2_SUIT_HELMET = register(new AntmanV2SuitItem.Helmet());
	public static final Item ANTMAN_V_2_SUIT_CHESTPLATE = register(new AntmanV2SuitItem.Chestplate());
	public static final Item ANTMAN_V_2_SUIT_LEGGINGS = register(new AntmanV2SuitItem.Leggings());
	public static final Item ANTMAN_V_2_SUIT_BOOTS = register(new AntmanV2SuitItem.Boots());
	public static final Item WOLVERINE_SUIT_HELMET = register(new WolverineSuitItem.Helmet());
	public static final Item WOLVERINE_SUIT_CHESTPLATE = register(new WolverineSuitItem.Chestplate());
	public static final Item WOLVERINE_SUIT_LEGGINGS = register(new WolverineSuitItem.Leggings());
	public static final Item WOLVERINE_SUIT_BOOTS = register(new WolverineSuitItem.Boots());
	public static final Item QUICKSILVER_SUIT_CHESTPLATE = register(new QuicksilverSuitItem.Chestplate());
	public static final Item QUICKSILVER_SUIT_LEGGINGS = register(new QuicksilverSuitItem.Leggings());
	public static final Item QUICKSILVER_SUIT_BOOTS = register(new QuicksilverSuitItem.Boots());
	public static final Item TASKMASTER_SUIT_HELMET = register(new TaskmasterSuitItem.Helmet());
	public static final Item TASKMASTER_SUIT_CHESTPLATE = register(new TaskmasterSuitItem.Chestplate());
	public static final Item TASKMASTER_SUIT_LEGGINGS = register(new TaskmasterSuitItem.Leggings());
	public static final Item TASKMASTER_SUIT_BOOTS = register(new TaskmasterSuitItem.Boots());
	public static final Item REINFORCED_LEATHER = register(new ReinforcedLeatherItem());
	public static final Item WAKANDA = register(new WakandaItem());
	public static final Item STAR_SPANGLED_MAN = register(new StarSpangledManItem());
	public static final Item DRIVING_WITH_THE_TOP_DOWN = register(new DrivingWithTheTopDownItem());
	public static final Item IRON_MAN_MARK_1_HELMET = register(new IronManMark1Item.Helmet());
	public static final Item IRON_MAN_MARK_1_CHESTPLATE = register(new IronManMark1Item.Chestplate());
	public static final Item IRON_MAN_MARK_1_LEGGINGS = register(new IronManMark1Item.Leggings());
	public static final Item IRON_MAN_MARK_1_BOOTS = register(new IronManMark1Item.Boots());
	public static final Item IRON_MAN_MARK_2_HELMET = register(new IronManMark2Item.Helmet());
	public static final Item IRON_MAN_MARK_2_CHESTPLATE = register(new IronManMark2Item.Chestplate());
	public static final Item IRON_MAN_MARK_2_LEGGINGS = register(new IronManMark2Item.Leggings());
	public static final Item IRON_MAN_MARK_2_BOOTS = register(new IronManMark2Item.Boots());
	public static final Item IRON_MAN_MARK_3_HELMET = register(new IronManMark3Item.Helmet());
	public static final Item IRON_MAN_MARK_3_CHESTPLATE = register(new IronManMark3Item.Chestplate());
	public static final Item IRON_MAN_MARK_3_LEGGINGS = register(new IronManMark3Item.Leggings());
	public static final Item IRON_MAN_MARK_3_BOOTS = register(new IronManMark3Item.Boots());
	public static final Item IRON_MAN_MARK_5_HELMET = register(new IronManMark5Item.Helmet());
	public static final Item IRON_MAN_MARK_5_CHESTPLATE = register(new IronManMark5Item.Chestplate());
	public static final Item IRON_MAN_MARK_5_LEGGINGS = register(new IronManMark5Item.Leggings());
	public static final Item IRON_MAN_MARK_5_BOOTS = register(new IronManMark5Item.Boots());
	public static final Item IRON_MAN_MARK_6_HELMET = register(new IronManMark6Item.Helmet());
	public static final Item IRON_MAN_MARK_6_CHESTPLATE = register(new IronManMark6Item.Chestplate());
	public static final Item IRON_MAN_MARK_6_LEGGINGS = register(new IronManMark6Item.Leggings());
	public static final Item IRON_MAN_MARK_6_BOOTS = register(new IronManMark6Item.Boots());
	public static final Item IRON_MAN_MARK_7_HELMET = register(new IronManMark7Item.Helmet());
	public static final Item IRON_MAN_MARK_7_CHESTPLATE = register(new IronManMark7Item.Chestplate());
	public static final Item IRON_MAN_MARK_7_LEGGINGS = register(new IronManMark7Item.Leggings());
	public static final Item IRON_MAN_MARK_7_BOOTS = register(new IronManMark7Item.Boots());
	public static final Item IRON_MAN_MARK_16_HELMET = register(new IronManMark16Item.Helmet());
	public static final Item IRON_MAN_MARK_16_CHESTPLATE = register(new IronManMark16Item.Chestplate());
	public static final Item IRON_MAN_MARK_16_LEGGINGS = register(new IronManMark16Item.Leggings());
	public static final Item IRON_MAN_MARK_16_BOOTS = register(new IronManMark16Item.Boots());
	public static final Item IRON_MAN_MARK_17_HELMET = register(new IronManMark17Item.Helmet());
	public static final Item IRON_MAN_MARK_17_CHESTPLATE = register(new IronManMark17Item.Chestplate());
	public static final Item IRON_MAN_MARK_17_LEGGINGS = register(new IronManMark17Item.Leggings());
	public static final Item IRON_MAN_MARK_17_BOOTS = register(new IronManMark17Item.Boots());
	public static final Item IRON_MAN_MARK_19_HELMET = register(new IronManMark19Item.Helmet());
	public static final Item IRON_MAN_MARK_19_CHESTPLATE = register(new IronManMark19Item.Chestplate());
	public static final Item IRON_MAN_MARK_19_LEGGINGS = register(new IronManMark19Item.Leggings());
	public static final Item IRON_MAN_MARK_19_BOOTS = register(new IronManMark19Item.Boots());
	public static final Item IRON_MAN_MARK_20_HELMET = register(new IronManMark20Item.Helmet());
	public static final Item IRON_MAN_MARK_20_CHESTPLATE = register(new IronManMark20Item.Chestplate());
	public static final Item IRON_MAN_MARK_20_LEGGINGS = register(new IronManMark20Item.Leggings());
	public static final Item IRON_MAN_MARK_20_BOOTS = register(new IronManMark20Item.Boots());
	public static final Item IRON_MAN_MARK_21_HELMET = register(new IronManMark21Item.Helmet());
	public static final Item IRON_MAN_MARK_21_CHESTPLATE = register(new IronManMark21Item.Chestplate());
	public static final Item IRON_MAN_MARK_21_LEGGINGS = register(new IronManMark21Item.Leggings());
	public static final Item IRON_MAN_MARK_21_BOOTS = register(new IronManMark21Item.Boots());
	public static final Item IRON_MAN_MARK_22_HELMET = register(new IronManMark22Item.Helmet());
	public static final Item IRON_MAN_MARK_22_CHESTPLATE = register(new IronManMark22Item.Chestplate());
	public static final Item IRON_MAN_MARK_22_LEGGINGS = register(new IronManMark22Item.Leggings());
	public static final Item IRON_MAN_MARK_22_BOOTS = register(new IronManMark22Item.Boots());
	public static final Item IRON_MAN_MARK_23_HELMET = register(new IronManMark23Item.Helmet());
	public static final Item IRON_MAN_MARK_23_CHESTPLATE = register(new IronManMark23Item.Chestplate());
	public static final Item IRON_MAN_MARK_23_LEGGINGS = register(new IronManMark23Item.Leggings());
	public static final Item IRON_MAN_MARK_23_BOOTS = register(new IronManMark23Item.Boots());
	public static final Item IRON_MAN_MARK_25_HELMET = register(new IronManMark25Item.Helmet());
	public static final Item IRON_MAN_MARK_25_CHESTPLATE = register(new IronManMark25Item.Chestplate());
	public static final Item IRON_MAN_MARK_25_LEGGINGS = register(new IronManMark25Item.Leggings());
	public static final Item IRON_MAN_MARK_25_BOOTS = register(new IronManMark25Item.Boots());
	public static final Item IRON_MAN_MARK_30_HELMET = register(new IronManMark30Item.Helmet());
	public static final Item IRON_MAN_MARK_30_CHESTPLATE = register(new IronManMark30Item.Chestplate());
	public static final Item IRON_MAN_MARK_30_LEGGINGS = register(new IronManMark30Item.Leggings());
	public static final Item IRON_MAN_MARK_30_BOOTS = register(new IronManMark30Item.Boots());
	public static final Item IRON_MAN_MARK_33_HELMET = register(new IronManMark33Item.Helmet());
	public static final Item IRON_MAN_MARK_33_CHESTPLATE = register(new IronManMark33Item.Chestplate());
	public static final Item IRON_MAN_MARK_33_LEGGINGS = register(new IronManMark33Item.Leggings());
	public static final Item IRON_MAN_MARK_33_BOOTS = register(new IronManMark33Item.Boots());
	public static final Item IRON_MAN_MARK_37_HELMET = register(new IronManMark37Item.Helmet());
	public static final Item IRON_MAN_MARK_37_CHESTPLATE = register(new IronManMark37Item.Chestplate());
	public static final Item IRON_MAN_MARK_37_LEGGINGS = register(new IronManMark37Item.Leggings());
	public static final Item IRON_MAN_MARK_37_BOOTS = register(new IronManMark37Item.Boots());
	public static final Item IRON_MAN_MARK_39_HELMET = register(new IronManMark39Item.Helmet());
	public static final Item IRON_MAN_MARK_39_CHESTPLATE = register(new IronManMark39Item.Chestplate());
	public static final Item IRON_MAN_MARK_39_LEGGINGS = register(new IronManMark39Item.Leggings());
	public static final Item IRON_MAN_MARK_39_BOOTS = register(new IronManMark39Item.Boots());
	public static final Item IRON_MAN_MARK_42_HELMET = register(new IronManMark42Item.Helmet());
	public static final Item IRON_MAN_MARK_42_CHESTPLATE = register(new IronManMark42Item.Chestplate());
	public static final Item IRON_MAN_MARK_42_LEGGINGS = register(new IronManMark42Item.Leggings());
	public static final Item IRON_MAN_MARK_42_BOOTS = register(new IronManMark42Item.Boots());
	public static final Item IRON_MAN_MARK_43_HELMET = register(new IronManMark43Item.Helmet());
	public static final Item IRON_MAN_MARK_43_CHESTPLATE = register(new IronManMark43Item.Chestplate());
	public static final Item IRON_MAN_MARK_43_LEGGINGS = register(new IronManMark43Item.Leggings());
	public static final Item IRON_MAN_MARK_43_BOOTS = register(new IronManMark43Item.Boots());
	public static final Item IRON_MAN_MARK_46_HELMET = register(new IronManMark46Item.Helmet());
	public static final Item IRON_MAN_MARK_46_CHESTPLATE = register(new IronManMark46Item.Chestplate());
	public static final Item IRON_MAN_MARK_46_LEGGINGS = register(new IronManMark46Item.Leggings());
	public static final Item IRON_MAN_MARK_46_BOOTS = register(new IronManMark46Item.Boots());
	public static final Item IRON_MAN_MARK_47_HELMET = register(new IronManMark47Item.Helmet());
	public static final Item IRON_MAN_MARK_47_CHESTPLATE = register(new IronManMark47Item.Chestplate());
	public static final Item IRON_MAN_MARK_47_LEGGINGS = register(new IronManMark47Item.Leggings());
	public static final Item IRON_MAN_MARK_47_BOOTS = register(new IronManMark47Item.Boots());
	public static final Item IRON_MAN_MARK_49_HELMET = register(new IronManMark49Item.Helmet());
	public static final Item IRON_MAN_MARK_49_CHESTPLATE = register(new IronManMark49Item.Chestplate());
	public static final Item IRON_MAN_MARK_49_LEGGINGS = register(new IronManMark49Item.Leggings());
	public static final Item IRON_MAN_MARK_49_BOOTS = register(new IronManMark49Item.Boots());
	public static final Item IRON_MAN_MARK_50_HELMET = register(new IronManMark50Item.Helmet());
	public static final Item IRON_MAN_MARK_50_CHESTPLATE = register(new IronManMark50Item.Chestplate());
	public static final Item IRON_MAN_MARK_50_LEGGINGS = register(new IronManMark50Item.Leggings());
	public static final Item IRON_MAN_MARK_50_BOOTS = register(new IronManMark50Item.Boots());
	public static final Item IRON_MAN_MARK_85_HELMET = register(new IronManMark85Item.Helmet());
	public static final Item IRON_MAN_MARK_85_CHESTPLATE = register(new IronManMark85Item.Chestplate());
	public static final Item IRON_MAN_MARK_85_LEGGINGS = register(new IronManMark85Item.Leggings());
	public static final Item IRON_MAN_MARK_85_BOOTS = register(new IronManMark85Item.Boots());
	public static final Item HEART_SHAPED_HERB_STAGE_1 = register(MarvelModBlocks.HEART_SHAPED_HERB_STAGE_1, null);
	public static final Item HEART_SHAPED_HERB_STAGE_2 = register(MarvelModBlocks.HEART_SHAPED_HERB_STAGE_2, null);
	public static final Item HEART_SHAPED_HERB_STAGE_3 = register(MarvelModBlocks.HEART_SHAPED_HERB_STAGE_3, null);
	public static final Item HEART_SHAPED_HERB_STAGE_4 = register(MarvelModBlocks.HEART_SHAPED_HERB_STAGE_4, null);
	public static final Item HEART_SHAPED_HERB_STAGE_5 = register(MarvelModBlocks.HEART_SHAPED_HERB_STAGE_5, null);
	public static final Item HEART_SHAPED_HERB_STAGE_6 = register(MarvelModBlocks.HEART_SHAPED_HERB_STAGE_6, null);
	public static final Item HEART_SHAPED_HERB_STAGE_7 = register(MarvelModBlocks.HEART_SHAPED_HERB_STAGE_7, null);
	public static final Item FLAME = register(new FlameItem());
	public static final Item FLAMETHROWER = register(new IronManFlamethrowerItem());
	public static final Item REPULSOR = register(new RepulsorItem());
	public static final Item REPULSOR_BULLET = register(new RepulsorBulletItem());
	public static final Item UNIBEAM = register(new UnibeamItem());
	public static final Item WAR_MACHINE_GUN = register(new WarMachineGunItem());
	public static final Item WEB_SHOOTER_TRAP = register(new WebShooterTrapItem());
	public static final Item TEMPORARY_WEB = register(MarvelModBlocks.TEMPORARY_WEB, null);
	public static final Item MARK_25_DRILL = register(new Mark25DrillItem());
	public static final Item CENTURION_BLADE = register(new CenturionBladeItem());
	public static final Item SHRINK_ITEM = register(new ShrinkItemItem());
	public static final Item GROW_ITEM = register(new GrowItemItem());
	public static final Item MARK_49_NANO_TOOL = register(new Mark49NanoToolItem());
	public static final Item MARK_50_NANO_TOOL = register(new Mark50NanoToolItem());;
	public static final Item MARK_85_NANO_TOOL = register(new Mark85NanoToolItem());
	public static final Item IRON_SPIDER_ARMS_CHESTPLATE = register(new IronSpiderArmsItem.Chestplate());
	public static final Item MJOLNIR_BLOCK = register(MarvelModBlocks.MJOLNIR_BLOCK, null);
	public static final Item ADAMANTIUM_CLAWS = register(new AdamantiumClawsItem());
	public static final Item THOR_ARMOR_CHESTPLATE = register(new ThorArmorItem.Chestplate());
	public static final Item THOR_ARMOR_LEGGINGS = register(new ThorArmorItem.Leggings());
	public static final Item THOR_ARMOR_BOOTS = register(new ThorArmorItem.Boots());
	public static final Item MARK_16_STEALTH_HELMET = register(new Mark16StealthItem.Helmet());
	public static final Item MARK_16_STEALTH_CHESTPLATE = register(new Mark16StealthItem.Chestplate());
	public static final Item MARK_16_STEALTH_LEGGINGS = register(new Mark16StealthItem.Leggings());
	public static final Item MARK_16_STEALTH_BOOTS = register(new Mark16StealthItem.Boots());
	public static final Item MARK_17_UNIBEAM = register(new Mark17UnibeamItem());

	private static Item register(Item item) {
		REGISTRY.add(item);
		return item;
	}

	private static Item register(Block block, @Nullable CreativeModeTab tab) {
		return register(new BlockItem(block, new Item.Properties().tab(tab)).setRegistryName(block.getRegistryName()));
	}

	@SubscribeEvent
	public static void registerItems(RegistryEvent.Register<Item> event) {
		event.getRegistry().registerAll(REGISTRY.toArray(new Item[0]));
	}
}
